-- | Bindings for @wayland.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.Core
  (
    WlCallbackEvent(..)
  , wlCallbackInterface
  , wlCallbackVersion
  , wlCallbackListen
  , WlCompositorEvent(..)
  , wlCompositorInterface
  , wlCompositorVersion
  , wlCompositorListen
  , wlCompositorCreateSurface
  , wlCompositorCreateRegion
  , WlShmPoolEvent(..)
  , wlShmPoolInterface
  , wlShmPoolVersion
  , wlShmPoolListen
  , wlShmPoolCreateBuffer
  , wlShmPoolDestroy
  , wlShmPoolResize
  , WlShmEvent(..)
  , wlShmInterface
  , wlShmVersion
  , wlShmListen
  , wlShmCreatePool
  , wlShmRelease
  , wlShmErrorInvalidFormat
  , wlShmErrorInvalidStride
  , wlShmErrorInvalidFd
  , wlShmFormatArgb8888
  , wlShmFormatXrgb8888
  , wlShmFormatC8
  , wlShmFormatRgb332
  , wlShmFormatBgr233
  , wlShmFormatXrgb4444
  , wlShmFormatXbgr4444
  , wlShmFormatRgbx4444
  , wlShmFormatBgrx4444
  , wlShmFormatArgb4444
  , wlShmFormatAbgr4444
  , wlShmFormatRgba4444
  , wlShmFormatBgra4444
  , wlShmFormatXrgb1555
  , wlShmFormatXbgr1555
  , wlShmFormatRgbx5551
  , wlShmFormatBgrx5551
  , wlShmFormatArgb1555
  , wlShmFormatAbgr1555
  , wlShmFormatRgba5551
  , wlShmFormatBgra5551
  , wlShmFormatRgb565
  , wlShmFormatBgr565
  , wlShmFormatRgb888
  , wlShmFormatBgr888
  , wlShmFormatXbgr8888
  , wlShmFormatRgbx8888
  , wlShmFormatBgrx8888
  , wlShmFormatAbgr8888
  , wlShmFormatRgba8888
  , wlShmFormatBgra8888
  , wlShmFormatXrgb2101010
  , wlShmFormatXbgr2101010
  , wlShmFormatRgbx1010102
  , wlShmFormatBgrx1010102
  , wlShmFormatArgb2101010
  , wlShmFormatAbgr2101010
  , wlShmFormatRgba1010102
  , wlShmFormatBgra1010102
  , wlShmFormatYuyv
  , wlShmFormatYvyu
  , wlShmFormatUyvy
  , wlShmFormatVyuy
  , wlShmFormatAyuv
  , wlShmFormatNv12
  , wlShmFormatNv21
  , wlShmFormatNv16
  , wlShmFormatNv61
  , wlShmFormatYuv410
  , wlShmFormatYvu410
  , wlShmFormatYuv411
  , wlShmFormatYvu411
  , wlShmFormatYuv420
  , wlShmFormatYvu420
  , wlShmFormatYuv422
  , wlShmFormatYvu422
  , wlShmFormatYuv444
  , wlShmFormatYvu444
  , wlShmFormatR8
  , wlShmFormatR16
  , wlShmFormatRg88
  , wlShmFormatGr88
  , wlShmFormatRg1616
  , wlShmFormatGr1616
  , wlShmFormatXrgb16161616f
  , wlShmFormatXbgr16161616f
  , wlShmFormatArgb16161616f
  , wlShmFormatAbgr16161616f
  , wlShmFormatXyuv8888
  , wlShmFormatVuy888
  , wlShmFormatVuy101010
  , wlShmFormatY210
  , wlShmFormatY212
  , wlShmFormatY216
  , wlShmFormatY410
  , wlShmFormatY412
  , wlShmFormatY416
  , wlShmFormatXvyu2101010
  , wlShmFormatXvyu1216161616
  , wlShmFormatXvyu16161616
  , wlShmFormatY0l0
  , wlShmFormatX0l0
  , wlShmFormatY0l2
  , wlShmFormatX0l2
  , wlShmFormatYuv4208bit
  , wlShmFormatYuv42010bit
  , wlShmFormatXrgb8888A8
  , wlShmFormatXbgr8888A8
  , wlShmFormatRgbx8888A8
  , wlShmFormatBgrx8888A8
  , wlShmFormatRgb888A8
  , wlShmFormatBgr888A8
  , wlShmFormatRgb565A8
  , wlShmFormatBgr565A8
  , wlShmFormatNv24
  , wlShmFormatNv42
  , wlShmFormatP210
  , wlShmFormatP010
  , wlShmFormatP012
  , wlShmFormatP016
  , wlShmFormatAxbxgxrx106106106106
  , wlShmFormatNv15
  , wlShmFormatQ410
  , wlShmFormatQ401
  , wlShmFormatXrgb16161616
  , wlShmFormatXbgr16161616
  , wlShmFormatArgb16161616
  , wlShmFormatAbgr16161616
  , wlShmFormatC1
  , wlShmFormatC2
  , wlShmFormatC4
  , wlShmFormatD1
  , wlShmFormatD2
  , wlShmFormatD4
  , wlShmFormatD8
  , wlShmFormatR1
  , wlShmFormatR2
  , wlShmFormatR4
  , wlShmFormatR10
  , wlShmFormatR12
  , wlShmFormatAvuy8888
  , wlShmFormatXvuy8888
  , wlShmFormatP030
  , WlBufferEvent(..)
  , wlBufferInterface
  , wlBufferVersion
  , wlBufferListen
  , wlBufferDestroy
  , WlSurfaceEvent(..)
  , wlSurfaceInterface
  , wlSurfaceVersion
  , wlSurfaceListen
  , wlSurfaceDestroy
  , wlSurfaceAttach
  , wlSurfaceDamage
  , wlSurfaceFrame
  , wlSurfaceSetOpaqueRegion
  , wlSurfaceSetInputRegion
  , wlSurfaceCommit
  , wlSurfaceSetBufferTransform
  , wlSurfaceSetBufferScale
  , wlSurfaceDamageBuffer
  , wlSurfaceOffset
  , wlSurfaceErrorInvalidScale
  , wlSurfaceErrorInvalidTransform
  , wlSurfaceErrorInvalidSize
  , wlSurfaceErrorInvalidOffset
  , wlSurfaceErrorDefunctRoleObject
  , WlSeatEvent(..)
  , wlSeatInterface
  , wlSeatVersion
  , wlSeatListen
  , wlSeatGetPointer
  , wlSeatGetKeyboard
  , wlSeatGetTouch
  , wlSeatRelease
  , wlSeatCapabilityPointer
  , wlSeatCapabilityKeyboard
  , wlSeatCapabilityTouch
  , wlSeatErrorMissingCapability
  , WlKeyboardEvent(..)
  , wlKeyboardInterface
  , wlKeyboardVersion
  , wlKeyboardListen
  , wlKeyboardRelease
  , wlKeyboardKeymapFormatNoKeymap
  , wlKeyboardKeymapFormatXkbV1
  , wlKeyboardKeyStateReleased
  , wlKeyboardKeyStatePressed
  , wlKeyboardKeyStateRepeated
  , WlOutputEvent(..)
  , wlOutputInterface
  , wlOutputVersion
  , wlOutputListen
  , wlOutputRelease
  , wlOutputSubpixelUnknown
  , wlOutputSubpixelNone
  , wlOutputSubpixelHorizontalRgb
  , wlOutputSubpixelHorizontalBgr
  , wlOutputSubpixelVerticalRgb
  , wlOutputSubpixelVerticalBgr
  , wlOutputTransformNormal
  , wlOutputTransform90
  , wlOutputTransform180
  , wlOutputTransform270
  , wlOutputTransformFlipped
  , wlOutputTransformFlipped90
  , wlOutputTransformFlipped180
  , wlOutputTransformFlipped270
  , wlOutputModeCurrent
  , wlOutputModePreferred
  , WlRegionEvent(..)
  , wlRegionInterface
  , wlRegionVersion
  , wlRegionListen
  , wlRegionDestroy
  , wlRegionAdd
  , wlRegionSubtract
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)
import System.Posix.Types (Fd)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- wl_callback (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlCallbackInterface :: ByteString
wlCallbackInterface = "wl_callback"

-- | The highest version these bindings were generated against.
wlCallbackVersion :: Word32
wlCallbackVersion = 1

-- | Events delivered to a @wl_callback@.
data WlCallbackEvent
  = WlCallbackDone !Word32
  | WlCallbackUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_callback@ object.
wlCallbackListen :: Connection -> ObjectId -> (WlCallbackEvent -> IO ()) -> IO ()
wlCallbackListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (WlCallbackDone <$> getWord32) body
    _ -> handler (WlCallbackUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_compositor (version 6)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlCompositorInterface :: ByteString
wlCompositorInterface = "wl_compositor"

-- | The highest version these bindings were generated against.
wlCompositorVersion :: Word32
wlCompositorVersion = 6

-- | @wl_compositor.create_surface@
wlCompositorCreateSurface :: Connection -> ObjectId -> IO ObjectId
wlCompositorCreateSurface conn self =
  do
    id_ <- newObject conn
    request conn self 0 (argObject id_)
    pure id_

-- | @wl_compositor.create_region@
wlCompositorCreateRegion :: Connection -> ObjectId -> IO ObjectId
wlCompositorCreateRegion conn self =
  do
    id_ <- newObject conn
    request conn self 1 (argObject id_)
    pure id_

-- | Events delivered to a @wl_compositor@.
data WlCompositorEvent
  = WlCompositorUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_compositor@ object.
wlCompositorListen :: Connection -> ObjectId -> (WlCompositorEvent -> IO ()) -> IO ()
wlCompositorListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (WlCompositorUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_shm_pool (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlShmPoolInterface :: ByteString
wlShmPoolInterface = "wl_shm_pool"

-- | The highest version these bindings were generated against.
wlShmPoolVersion :: Word32
wlShmPoolVersion = 2

-- | @wl_shm_pool.create_buffer@
wlShmPoolCreateBuffer :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> Word32 -> IO ObjectId
wlShmPoolCreateBuffer conn self offset width height stride format =
  do
    id_ <- newObject conn
    request conn self 0 (argObject id_ <> argInt offset <> argInt width <> argInt height <> argInt stride <> argUInt format)
    pure id_

-- | @wl_shm_pool.destroy@
wlShmPoolDestroy :: Connection -> ObjectId -> IO ()
wlShmPoolDestroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | @wl_shm_pool.resize@
wlShmPoolResize :: Connection -> ObjectId -> Int32 -> IO ()
wlShmPoolResize conn self size =
  request conn self 2 (argInt size)

-- | Events delivered to a @wl_shm_pool@.
data WlShmPoolEvent
  = WlShmPoolUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_shm_pool@ object.
wlShmPoolListen :: Connection -> ObjectId -> (WlShmPoolEvent -> IO ()) -> IO ()
wlShmPoolListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (WlShmPoolUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_shm (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlShmInterface :: ByteString
wlShmInterface = "wl_shm"

-- | The highest version these bindings were generated against.
wlShmVersion :: Word32
wlShmVersion = 2

-- | @wl_shm.error.invalid_format@
wlShmErrorInvalidFormat :: Word32
wlShmErrorInvalidFormat = 0

-- | @wl_shm.error.invalid_stride@
wlShmErrorInvalidStride :: Word32
wlShmErrorInvalidStride = 1

-- | @wl_shm.error.invalid_fd@
wlShmErrorInvalidFd :: Word32
wlShmErrorInvalidFd = 2

-- | @wl_shm.format.argb8888@
wlShmFormatArgb8888 :: Word32
wlShmFormatArgb8888 = 0

-- | @wl_shm.format.xrgb8888@
wlShmFormatXrgb8888 :: Word32
wlShmFormatXrgb8888 = 1

-- | @wl_shm.format.c8@
wlShmFormatC8 :: Word32
wlShmFormatC8 = 538982467

-- | @wl_shm.format.rgb332@
wlShmFormatRgb332 :: Word32
wlShmFormatRgb332 = 943867730

-- | @wl_shm.format.bgr233@
wlShmFormatBgr233 :: Word32
wlShmFormatBgr233 = 944916290

-- | @wl_shm.format.xrgb4444@
wlShmFormatXrgb4444 :: Word32
wlShmFormatXrgb4444 = 842093144

-- | @wl_shm.format.xbgr4444@
wlShmFormatXbgr4444 :: Word32
wlShmFormatXbgr4444 = 842089048

-- | @wl_shm.format.rgbx4444@
wlShmFormatRgbx4444 :: Word32
wlShmFormatRgbx4444 = 842094674

-- | @wl_shm.format.bgrx4444@
wlShmFormatBgrx4444 :: Word32
wlShmFormatBgrx4444 = 842094658

-- | @wl_shm.format.argb4444@
wlShmFormatArgb4444 :: Word32
wlShmFormatArgb4444 = 842093121

-- | @wl_shm.format.abgr4444@
wlShmFormatAbgr4444 :: Word32
wlShmFormatAbgr4444 = 842089025

-- | @wl_shm.format.rgba4444@
wlShmFormatRgba4444 :: Word32
wlShmFormatRgba4444 = 842088786

-- | @wl_shm.format.bgra4444@
wlShmFormatBgra4444 :: Word32
wlShmFormatBgra4444 = 842088770

-- | @wl_shm.format.xrgb1555@
wlShmFormatXrgb1555 :: Word32
wlShmFormatXrgb1555 = 892424792

-- | @wl_shm.format.xbgr1555@
wlShmFormatXbgr1555 :: Word32
wlShmFormatXbgr1555 = 892420696

-- | @wl_shm.format.rgbx5551@
wlShmFormatRgbx5551 :: Word32
wlShmFormatRgbx5551 = 892426322

-- | @wl_shm.format.bgrx5551@
wlShmFormatBgrx5551 :: Word32
wlShmFormatBgrx5551 = 892426306

-- | @wl_shm.format.argb1555@
wlShmFormatArgb1555 :: Word32
wlShmFormatArgb1555 = 892424769

-- | @wl_shm.format.abgr1555@
wlShmFormatAbgr1555 :: Word32
wlShmFormatAbgr1555 = 892420673

-- | @wl_shm.format.rgba5551@
wlShmFormatRgba5551 :: Word32
wlShmFormatRgba5551 = 892420434

-- | @wl_shm.format.bgra5551@
wlShmFormatBgra5551 :: Word32
wlShmFormatBgra5551 = 892420418

-- | @wl_shm.format.rgb565@
wlShmFormatRgb565 :: Word32
wlShmFormatRgb565 = 909199186

-- | @wl_shm.format.bgr565@
wlShmFormatBgr565 :: Word32
wlShmFormatBgr565 = 909199170

-- | @wl_shm.format.rgb888@
wlShmFormatRgb888 :: Word32
wlShmFormatRgb888 = 875710290

-- | @wl_shm.format.bgr888@
wlShmFormatBgr888 :: Word32
wlShmFormatBgr888 = 875710274

-- | @wl_shm.format.xbgr8888@
wlShmFormatXbgr8888 :: Word32
wlShmFormatXbgr8888 = 875709016

-- | @wl_shm.format.rgbx8888@
wlShmFormatRgbx8888 :: Word32
wlShmFormatRgbx8888 = 875714642

-- | @wl_shm.format.bgrx8888@
wlShmFormatBgrx8888 :: Word32
wlShmFormatBgrx8888 = 875714626

-- | @wl_shm.format.abgr8888@
wlShmFormatAbgr8888 :: Word32
wlShmFormatAbgr8888 = 875708993

-- | @wl_shm.format.rgba8888@
wlShmFormatRgba8888 :: Word32
wlShmFormatRgba8888 = 875708754

-- | @wl_shm.format.bgra8888@
wlShmFormatBgra8888 :: Word32
wlShmFormatBgra8888 = 875708738

-- | @wl_shm.format.xrgb2101010@
wlShmFormatXrgb2101010 :: Word32
wlShmFormatXrgb2101010 = 808669784

-- | @wl_shm.format.xbgr2101010@
wlShmFormatXbgr2101010 :: Word32
wlShmFormatXbgr2101010 = 808665688

-- | @wl_shm.format.rgbx1010102@
wlShmFormatRgbx1010102 :: Word32
wlShmFormatRgbx1010102 = 808671314

-- | @wl_shm.format.bgrx1010102@
wlShmFormatBgrx1010102 :: Word32
wlShmFormatBgrx1010102 = 808671298

-- | @wl_shm.format.argb2101010@
wlShmFormatArgb2101010 :: Word32
wlShmFormatArgb2101010 = 808669761

-- | @wl_shm.format.abgr2101010@
wlShmFormatAbgr2101010 :: Word32
wlShmFormatAbgr2101010 = 808665665

-- | @wl_shm.format.rgba1010102@
wlShmFormatRgba1010102 :: Word32
wlShmFormatRgba1010102 = 808665426

-- | @wl_shm.format.bgra1010102@
wlShmFormatBgra1010102 :: Word32
wlShmFormatBgra1010102 = 808665410

-- | @wl_shm.format.yuyv@
wlShmFormatYuyv :: Word32
wlShmFormatYuyv = 1448695129

-- | @wl_shm.format.yvyu@
wlShmFormatYvyu :: Word32
wlShmFormatYvyu = 1431918169

-- | @wl_shm.format.uyvy@
wlShmFormatUyvy :: Word32
wlShmFormatUyvy = 1498831189

-- | @wl_shm.format.vyuy@
wlShmFormatVyuy :: Word32
wlShmFormatVyuy = 1498765654

-- | @wl_shm.format.ayuv@
wlShmFormatAyuv :: Word32
wlShmFormatAyuv = 1448433985

-- | @wl_shm.format.nv12@
wlShmFormatNv12 :: Word32
wlShmFormatNv12 = 842094158

-- | @wl_shm.format.nv21@
wlShmFormatNv21 :: Word32
wlShmFormatNv21 = 825382478

-- | @wl_shm.format.nv16@
wlShmFormatNv16 :: Word32
wlShmFormatNv16 = 909203022

-- | @wl_shm.format.nv61@
wlShmFormatNv61 :: Word32
wlShmFormatNv61 = 825644622

-- | @wl_shm.format.yuv410@
wlShmFormatYuv410 :: Word32
wlShmFormatYuv410 = 961959257

-- | @wl_shm.format.yvu410@
wlShmFormatYvu410 :: Word32
wlShmFormatYvu410 = 961893977

-- | @wl_shm.format.yuv411@
wlShmFormatYuv411 :: Word32
wlShmFormatYuv411 = 825316697

-- | @wl_shm.format.yvu411@
wlShmFormatYvu411 :: Word32
wlShmFormatYvu411 = 825316953

-- | @wl_shm.format.yuv420@
wlShmFormatYuv420 :: Word32
wlShmFormatYuv420 = 842093913

-- | @wl_shm.format.yvu420@
wlShmFormatYvu420 :: Word32
wlShmFormatYvu420 = 842094169

-- | @wl_shm.format.yuv422@
wlShmFormatYuv422 :: Word32
wlShmFormatYuv422 = 909202777

-- | @wl_shm.format.yvu422@
wlShmFormatYvu422 :: Word32
wlShmFormatYvu422 = 909203033

-- | @wl_shm.format.yuv444@
wlShmFormatYuv444 :: Word32
wlShmFormatYuv444 = 875713881

-- | @wl_shm.format.yvu444@
wlShmFormatYvu444 :: Word32
wlShmFormatYvu444 = 875714137

-- | @wl_shm.format.r8@
wlShmFormatR8 :: Word32
wlShmFormatR8 = 538982482

-- | @wl_shm.format.r16@
wlShmFormatR16 :: Word32
wlShmFormatR16 = 540422482

-- | @wl_shm.format.rg88@
wlShmFormatRg88 :: Word32
wlShmFormatRg88 = 943212370

-- | @wl_shm.format.gr88@
wlShmFormatGr88 :: Word32
wlShmFormatGr88 = 943215175

-- | @wl_shm.format.rg1616@
wlShmFormatRg1616 :: Word32
wlShmFormatRg1616 = 842221394

-- | @wl_shm.format.gr1616@
wlShmFormatGr1616 :: Word32
wlShmFormatGr1616 = 842224199

-- | @wl_shm.format.xrgb16161616f@
wlShmFormatXrgb16161616f :: Word32
wlShmFormatXrgb16161616f = 1211388504

-- | @wl_shm.format.xbgr16161616f@
wlShmFormatXbgr16161616f :: Word32
wlShmFormatXbgr16161616f = 1211384408

-- | @wl_shm.format.argb16161616f@
wlShmFormatArgb16161616f :: Word32
wlShmFormatArgb16161616f = 1211388481

-- | @wl_shm.format.abgr16161616f@
wlShmFormatAbgr16161616f :: Word32
wlShmFormatAbgr16161616f = 1211384385

-- | @wl_shm.format.xyuv8888@
wlShmFormatXyuv8888 :: Word32
wlShmFormatXyuv8888 = 1448434008

-- | @wl_shm.format.vuy888@
wlShmFormatVuy888 :: Word32
wlShmFormatVuy888 = 875713878

-- | @wl_shm.format.vuy101010@
wlShmFormatVuy101010 :: Word32
wlShmFormatVuy101010 = 808670550

-- | @wl_shm.format.y210@
wlShmFormatY210 :: Word32
wlShmFormatY210 = 808530521

-- | @wl_shm.format.y212@
wlShmFormatY212 :: Word32
wlShmFormatY212 = 842084953

-- | @wl_shm.format.y216@
wlShmFormatY216 :: Word32
wlShmFormatY216 = 909193817

-- | @wl_shm.format.y410@
wlShmFormatY410 :: Word32
wlShmFormatY410 = 808531033

-- | @wl_shm.format.y412@
wlShmFormatY412 :: Word32
wlShmFormatY412 = 842085465

-- | @wl_shm.format.y416@
wlShmFormatY416 :: Word32
wlShmFormatY416 = 909194329

-- | @wl_shm.format.xvyu2101010@
wlShmFormatXvyu2101010 :: Word32
wlShmFormatXvyu2101010 = 808670808

-- | @wl_shm.format.xvyu12_16161616@
wlShmFormatXvyu1216161616 :: Word32
wlShmFormatXvyu1216161616 = 909334104

-- | @wl_shm.format.xvyu16161616@
wlShmFormatXvyu16161616 :: Word32
wlShmFormatXvyu16161616 = 942954072

-- | @wl_shm.format.y0l0@
wlShmFormatY0l0 :: Word32
wlShmFormatY0l0 = 810299481

-- | @wl_shm.format.x0l0@
wlShmFormatX0l0 :: Word32
wlShmFormatX0l0 = 810299480

-- | @wl_shm.format.y0l2@
wlShmFormatY0l2 :: Word32
wlShmFormatY0l2 = 843853913

-- | @wl_shm.format.x0l2@
wlShmFormatX0l2 :: Word32
wlShmFormatX0l2 = 843853912

-- | @wl_shm.format.yuv420_8bit@
wlShmFormatYuv4208bit :: Word32
wlShmFormatYuv4208bit = 942691673

-- | @wl_shm.format.yuv420_10bit@
wlShmFormatYuv42010bit :: Word32
wlShmFormatYuv42010bit = 808539481

-- | @wl_shm.format.xrgb8888_a8@
wlShmFormatXrgb8888A8 :: Word32
wlShmFormatXrgb8888A8 = 943805016

-- | @wl_shm.format.xbgr8888_a8@
wlShmFormatXbgr8888A8 :: Word32
wlShmFormatXbgr8888A8 = 943800920

-- | @wl_shm.format.rgbx8888_a8@
wlShmFormatRgbx8888A8 :: Word32
wlShmFormatRgbx8888A8 = 943806546

-- | @wl_shm.format.bgrx8888_a8@
wlShmFormatBgrx8888A8 :: Word32
wlShmFormatBgrx8888A8 = 943806530

-- | @wl_shm.format.rgb888_a8@
wlShmFormatRgb888A8 :: Word32
wlShmFormatRgb888A8 = 943798354

-- | @wl_shm.format.bgr888_a8@
wlShmFormatBgr888A8 :: Word32
wlShmFormatBgr888A8 = 943798338

-- | @wl_shm.format.rgb565_a8@
wlShmFormatRgb565A8 :: Word32
wlShmFormatRgb565A8 = 943797586

-- | @wl_shm.format.bgr565_a8@
wlShmFormatBgr565A8 :: Word32
wlShmFormatBgr565A8 = 943797570

-- | @wl_shm.format.nv24@
wlShmFormatNv24 :: Word32
wlShmFormatNv24 = 875714126

-- | @wl_shm.format.nv42@
wlShmFormatNv42 :: Word32
wlShmFormatNv42 = 842290766

-- | @wl_shm.format.p210@
wlShmFormatP210 :: Word32
wlShmFormatP210 = 808530512

-- | @wl_shm.format.p010@
wlShmFormatP010 :: Word32
wlShmFormatP010 = 808530000

-- | @wl_shm.format.p012@
wlShmFormatP012 :: Word32
wlShmFormatP012 = 842084432

-- | @wl_shm.format.p016@
wlShmFormatP016 :: Word32
wlShmFormatP016 = 909193296

-- | @wl_shm.format.axbxgxrx106106106106@
wlShmFormatAxbxgxrx106106106106 :: Word32
wlShmFormatAxbxgxrx106106106106 = 808534593

-- | @wl_shm.format.nv15@
wlShmFormatNv15 :: Word32
wlShmFormatNv15 = 892425806

-- | @wl_shm.format.q410@
wlShmFormatQ410 :: Word32
wlShmFormatQ410 = 808531025

-- | @wl_shm.format.q401@
wlShmFormatQ401 :: Word32
wlShmFormatQ401 = 825242705

-- | @wl_shm.format.xrgb16161616@
wlShmFormatXrgb16161616 :: Word32
wlShmFormatXrgb16161616 = 942953048

-- | @wl_shm.format.xbgr16161616@
wlShmFormatXbgr16161616 :: Word32
wlShmFormatXbgr16161616 = 942948952

-- | @wl_shm.format.argb16161616@
wlShmFormatArgb16161616 :: Word32
wlShmFormatArgb16161616 = 942953025

-- | @wl_shm.format.abgr16161616@
wlShmFormatAbgr16161616 :: Word32
wlShmFormatAbgr16161616 = 942948929

-- | @wl_shm.format.c1@
wlShmFormatC1 :: Word32
wlShmFormatC1 = 538980675

-- | @wl_shm.format.c2@
wlShmFormatC2 :: Word32
wlShmFormatC2 = 538980931

-- | @wl_shm.format.c4@
wlShmFormatC4 :: Word32
wlShmFormatC4 = 538981443

-- | @wl_shm.format.d1@
wlShmFormatD1 :: Word32
wlShmFormatD1 = 538980676

-- | @wl_shm.format.d2@
wlShmFormatD2 :: Word32
wlShmFormatD2 = 538980932

-- | @wl_shm.format.d4@
wlShmFormatD4 :: Word32
wlShmFormatD4 = 538981444

-- | @wl_shm.format.d8@
wlShmFormatD8 :: Word32
wlShmFormatD8 = 538982468

-- | @wl_shm.format.r1@
wlShmFormatR1 :: Word32
wlShmFormatR1 = 538980690

-- | @wl_shm.format.r2@
wlShmFormatR2 :: Word32
wlShmFormatR2 = 538980946

-- | @wl_shm.format.r4@
wlShmFormatR4 :: Word32
wlShmFormatR4 = 538981458

-- | @wl_shm.format.r10@
wlShmFormatR10 :: Word32
wlShmFormatR10 = 540029266

-- | @wl_shm.format.r12@
wlShmFormatR12 :: Word32
wlShmFormatR12 = 540160338

-- | @wl_shm.format.avuy8888@
wlShmFormatAvuy8888 :: Word32
wlShmFormatAvuy8888 = 1498764865

-- | @wl_shm.format.xvuy8888@
wlShmFormatXvuy8888 :: Word32
wlShmFormatXvuy8888 = 1498764888

-- | @wl_shm.format.p030@
wlShmFormatP030 :: Word32
wlShmFormatP030 = 808661072

-- | @wl_shm.create_pool@
wlShmCreatePool :: Connection -> ObjectId -> Fd -> Int32 -> IO ObjectId
wlShmCreatePool conn self fd size =
  do
    id_ <- newObject conn
    requestWithFds conn self 0 (argObject id_ <> mempty <> argInt size) [fd]
    pure id_

-- | @wl_shm.release@
-- Since version 2.
wlShmRelease :: Connection -> ObjectId -> IO ()
wlShmRelease conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | Events delivered to a @wl_shm@.
data WlShmEvent
  = WlShmFormat !Word32
  | WlShmUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_shm@ object.
wlShmListen :: Connection -> ObjectId -> (WlShmEvent -> IO ()) -> IO ()
wlShmListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (WlShmFormat <$> getWord32) body
    _ -> handler (WlShmUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_buffer (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlBufferInterface :: ByteString
wlBufferInterface = "wl_buffer"

-- | The highest version these bindings were generated against.
wlBufferVersion :: Word32
wlBufferVersion = 1

-- | @wl_buffer.destroy@
wlBufferDestroy :: Connection -> ObjectId -> IO ()
wlBufferDestroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | Events delivered to a @wl_buffer@.
data WlBufferEvent
  = WlBufferRelease
  | WlBufferUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_buffer@ object.
wlBufferListen :: Connection -> ObjectId -> (WlBufferEvent -> IO ()) -> IO ()
wlBufferListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler WlBufferRelease
    _ -> handler (WlBufferUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_surface (version 6)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlSurfaceInterface :: ByteString
wlSurfaceInterface = "wl_surface"

-- | The highest version these bindings were generated against.
wlSurfaceVersion :: Word32
wlSurfaceVersion = 6

-- | @wl_surface.error.invalid_scale@
wlSurfaceErrorInvalidScale :: Word32
wlSurfaceErrorInvalidScale = 0

-- | @wl_surface.error.invalid_transform@
wlSurfaceErrorInvalidTransform :: Word32
wlSurfaceErrorInvalidTransform = 1

-- | @wl_surface.error.invalid_size@
wlSurfaceErrorInvalidSize :: Word32
wlSurfaceErrorInvalidSize = 2

-- | @wl_surface.error.invalid_offset@
wlSurfaceErrorInvalidOffset :: Word32
wlSurfaceErrorInvalidOffset = 3

-- | @wl_surface.error.defunct_role_object@
wlSurfaceErrorDefunctRoleObject :: Word32
wlSurfaceErrorDefunctRoleObject = 4

-- | @wl_surface.destroy@
wlSurfaceDestroy :: Connection -> ObjectId -> IO ()
wlSurfaceDestroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @wl_surface.attach@
wlSurfaceAttach :: Connection -> ObjectId -> ObjectId -> Int32 -> Int32 -> IO ()
wlSurfaceAttach conn self buffer x y =
  request conn self 1 (argObject buffer <> argInt x <> argInt y)

-- | @wl_surface.damage@
wlSurfaceDamage :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
wlSurfaceDamage conn self x y width height =
  request conn self 2 (argInt x <> argInt y <> argInt width <> argInt height)

-- | @wl_surface.frame@
wlSurfaceFrame :: Connection -> ObjectId -> IO ObjectId
wlSurfaceFrame conn self =
  do
    callback <- newObject conn
    request conn self 3 (argObject callback)
    pure callback

-- | @wl_surface.set_opaque_region@
wlSurfaceSetOpaqueRegion :: Connection -> ObjectId -> ObjectId -> IO ()
wlSurfaceSetOpaqueRegion conn self region =
  request conn self 4 (argObject region)

-- | @wl_surface.set_input_region@
wlSurfaceSetInputRegion :: Connection -> ObjectId -> ObjectId -> IO ()
wlSurfaceSetInputRegion conn self region =
  request conn self 5 (argObject region)

-- | @wl_surface.commit@
wlSurfaceCommit :: Connection -> ObjectId -> IO ()
wlSurfaceCommit conn self =
  request conn self 6 (mempty)

-- | @wl_surface.set_buffer_transform@
-- Since version 2.
wlSurfaceSetBufferTransform :: Connection -> ObjectId -> Int32 -> IO ()
wlSurfaceSetBufferTransform conn self transform =
  request conn self 7 (argInt transform)

-- | @wl_surface.set_buffer_scale@
-- Since version 3.
wlSurfaceSetBufferScale :: Connection -> ObjectId -> Int32 -> IO ()
wlSurfaceSetBufferScale conn self scale =
  request conn self 8 (argInt scale)

-- | @wl_surface.damage_buffer@
-- Since version 4.
wlSurfaceDamageBuffer :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
wlSurfaceDamageBuffer conn self x y width height =
  request conn self 9 (argInt x <> argInt y <> argInt width <> argInt height)

-- | @wl_surface.offset@
-- Since version 5.
wlSurfaceOffset :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
wlSurfaceOffset conn self x y =
  request conn self 10 (argInt x <> argInt y)

-- | Events delivered to a @wl_surface@.
data WlSurfaceEvent
  = WlSurfaceEnter !ObjectId
  | WlSurfaceLeave !ObjectId
  | WlSurfacePreferredBufferScale !Int32
  | WlSurfacePreferredBufferTransform !Word32
  | WlSurfaceUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_surface@ object.
wlSurfaceListen :: Connection -> ObjectId -> (WlSurfaceEvent -> IO ()) -> IO ()
wlSurfaceListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (WlSurfaceEnter <$> getObject) body
    1 ->
      handler =<< decode (WlSurfaceLeave <$> getObject) body
    2 ->
      handler =<< decode (WlSurfacePreferredBufferScale <$> getInt) body
    3 ->
      handler =<< decode (WlSurfacePreferredBufferTransform <$> getWord32) body
    _ -> handler (WlSurfaceUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_seat (version 10)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlSeatInterface :: ByteString
wlSeatInterface = "wl_seat"

-- | The highest version these bindings were generated against.
wlSeatVersion :: Word32
wlSeatVersion = 10

-- | @wl_seat.capability.pointer@
wlSeatCapabilityPointer :: Word32
wlSeatCapabilityPointer = 1

-- | @wl_seat.capability.keyboard@
wlSeatCapabilityKeyboard :: Word32
wlSeatCapabilityKeyboard = 2

-- | @wl_seat.capability.touch@
wlSeatCapabilityTouch :: Word32
wlSeatCapabilityTouch = 4

-- | @wl_seat.error.missing_capability@
wlSeatErrorMissingCapability :: Word32
wlSeatErrorMissingCapability = 0

-- | @wl_seat.get_pointer@
wlSeatGetPointer :: Connection -> ObjectId -> IO ObjectId
wlSeatGetPointer conn self =
  do
    id_ <- newObject conn
    request conn self 0 (argObject id_)
    pure id_

-- | @wl_seat.get_keyboard@
wlSeatGetKeyboard :: Connection -> ObjectId -> IO ObjectId
wlSeatGetKeyboard conn self =
  do
    id_ <- newObject conn
    request conn self 1 (argObject id_)
    pure id_

-- | @wl_seat.get_touch@
wlSeatGetTouch :: Connection -> ObjectId -> IO ObjectId
wlSeatGetTouch conn self =
  do
    id_ <- newObject conn
    request conn self 2 (argObject id_)
    pure id_

-- | @wl_seat.release@
-- Since version 5.
wlSeatRelease :: Connection -> ObjectId -> IO ()
wlSeatRelease conn self =
  request conn self 3 (mempty)
    >> freeObject conn self

-- | Events delivered to a @wl_seat@.
data WlSeatEvent
  = WlSeatCapabilities !Word32
  | WlSeatName !ByteString
  | WlSeatUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_seat@ object.
wlSeatListen :: Connection -> ObjectId -> (WlSeatEvent -> IO ()) -> IO ()
wlSeatListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (WlSeatCapabilities <$> getWord32) body
    1 ->
      handler =<< decode (WlSeatName <$> getString) body
    _ -> handler (WlSeatUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_keyboard (version 10)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlKeyboardInterface :: ByteString
wlKeyboardInterface = "wl_keyboard"

-- | The highest version these bindings were generated against.
wlKeyboardVersion :: Word32
wlKeyboardVersion = 10

-- | @wl_keyboard.keymap_format.no_keymap@
wlKeyboardKeymapFormatNoKeymap :: Word32
wlKeyboardKeymapFormatNoKeymap = 0

-- | @wl_keyboard.keymap_format.xkb_v1@
wlKeyboardKeymapFormatXkbV1 :: Word32
wlKeyboardKeymapFormatXkbV1 = 1

-- | @wl_keyboard.key_state.released@
wlKeyboardKeyStateReleased :: Word32
wlKeyboardKeyStateReleased = 0

-- | @wl_keyboard.key_state.pressed@
wlKeyboardKeyStatePressed :: Word32
wlKeyboardKeyStatePressed = 1

-- | @wl_keyboard.key_state.repeated@
wlKeyboardKeyStateRepeated :: Word32
wlKeyboardKeyStateRepeated = 2

-- | @wl_keyboard.release@
-- Since version 3.
wlKeyboardRelease :: Connection -> ObjectId -> IO ()
wlKeyboardRelease conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | Events delivered to a @wl_keyboard@.
data WlKeyboardEvent
  = WlKeyboardKeymap !Word32 !Fd !Word32
  | WlKeyboardEnter !Word32 !ObjectId !ByteString
  | WlKeyboardLeave !Word32 !ObjectId
  | WlKeyboardKey !Word32 !Word32 !Word32 !Word32
  | WlKeyboardModifiers !Word32 !Word32 !Word32 !Word32 !Word32
  | WlKeyboardRepeatInfo !Int32 !Int32
  | WlKeyboardUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_keyboard@ object.
wlKeyboardListen :: Connection -> ObjectId -> (WlKeyboardEvent -> IO ()) -> IO ()
wlKeyboardListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> do
      fd_fd <- takeFdOrFail conn "fd"
      handler =<< decode (WlKeyboardKeymap <$> getWord32 <*> pure fd_fd <*> getWord32) body
    1 ->
      handler =<< decode (WlKeyboardEnter <$> getWord32 <*> getObject <*> getArray) body
    2 ->
      handler =<< decode (WlKeyboardLeave <$> getWord32 <*> getObject) body
    3 ->
      handler =<< decode (WlKeyboardKey <$> getWord32 <*> getWord32 <*> getWord32 <*> getWord32) body
    4 ->
      handler =<< decode (WlKeyboardModifiers <$> getWord32 <*> getWord32 <*> getWord32 <*> getWord32 <*> getWord32) body
    5 ->
      handler =<< decode (WlKeyboardRepeatInfo <$> getInt <*> getInt) body
    _ -> handler (WlKeyboardUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_output (version 4)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlOutputInterface :: ByteString
wlOutputInterface = "wl_output"

-- | The highest version these bindings were generated against.
wlOutputVersion :: Word32
wlOutputVersion = 4

-- | @wl_output.subpixel.unknown@
wlOutputSubpixelUnknown :: Word32
wlOutputSubpixelUnknown = 0

-- | @wl_output.subpixel.none@
wlOutputSubpixelNone :: Word32
wlOutputSubpixelNone = 1

-- | @wl_output.subpixel.horizontal_rgb@
wlOutputSubpixelHorizontalRgb :: Word32
wlOutputSubpixelHorizontalRgb = 2

-- | @wl_output.subpixel.horizontal_bgr@
wlOutputSubpixelHorizontalBgr :: Word32
wlOutputSubpixelHorizontalBgr = 3

-- | @wl_output.subpixel.vertical_rgb@
wlOutputSubpixelVerticalRgb :: Word32
wlOutputSubpixelVerticalRgb = 4

-- | @wl_output.subpixel.vertical_bgr@
wlOutputSubpixelVerticalBgr :: Word32
wlOutputSubpixelVerticalBgr = 5

-- | @wl_output.transform.normal@
wlOutputTransformNormal :: Word32
wlOutputTransformNormal = 0

-- | @wl_output.transform.90@
wlOutputTransform90 :: Word32
wlOutputTransform90 = 1

-- | @wl_output.transform.180@
wlOutputTransform180 :: Word32
wlOutputTransform180 = 2

-- | @wl_output.transform.270@
wlOutputTransform270 :: Word32
wlOutputTransform270 = 3

-- | @wl_output.transform.flipped@
wlOutputTransformFlipped :: Word32
wlOutputTransformFlipped = 4

-- | @wl_output.transform.flipped_90@
wlOutputTransformFlipped90 :: Word32
wlOutputTransformFlipped90 = 5

-- | @wl_output.transform.flipped_180@
wlOutputTransformFlipped180 :: Word32
wlOutputTransformFlipped180 = 6

-- | @wl_output.transform.flipped_270@
wlOutputTransformFlipped270 :: Word32
wlOutputTransformFlipped270 = 7

-- | @wl_output.mode.current@
wlOutputModeCurrent :: Word32
wlOutputModeCurrent = 1

-- | @wl_output.mode.preferred@
wlOutputModePreferred :: Word32
wlOutputModePreferred = 2

-- | @wl_output.release@
-- Since version 3.
wlOutputRelease :: Connection -> ObjectId -> IO ()
wlOutputRelease conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | Events delivered to a @wl_output@.
data WlOutputEvent
  = WlOutputGeometry !Int32 !Int32 !Int32 !Int32 !Int32 !ByteString !ByteString !Int32
  | WlOutputMode !Word32 !Int32 !Int32 !Int32
  | WlOutputDone
  | WlOutputScale !Int32
  | WlOutputName !ByteString
  | WlOutputDescription !ByteString
  | WlOutputUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_output@ object.
wlOutputListen :: Connection -> ObjectId -> (WlOutputEvent -> IO ()) -> IO ()
wlOutputListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (WlOutputGeometry <$> getInt <*> getInt <*> getInt <*> getInt <*> getInt <*> getString <*> getString <*> getInt) body
    1 ->
      handler =<< decode (WlOutputMode <$> getWord32 <*> getInt <*> getInt <*> getInt) body
    2 -> handler WlOutputDone
    3 ->
      handler =<< decode (WlOutputScale <$> getInt) body
    4 ->
      handler =<< decode (WlOutputName <$> getString) body
    5 ->
      handler =<< decode (WlOutputDescription <$> getString) body
    _ -> handler (WlOutputUnknown opcode body)

--------------------------------------------------------------------------------
-- wl_region (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
wlRegionInterface :: ByteString
wlRegionInterface = "wl_region"

-- | The highest version these bindings were generated against.
wlRegionVersion :: Word32
wlRegionVersion = 1

-- | @wl_region.destroy@
wlRegionDestroy :: Connection -> ObjectId -> IO ()
wlRegionDestroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @wl_region.add@
wlRegionAdd :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
wlRegionAdd conn self x y width height =
  request conn self 1 (argInt x <> argInt y <> argInt width <> argInt height)

-- | @wl_region.subtract@
wlRegionSubtract :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
wlRegionSubtract conn self x y width height =
  request conn self 2 (argInt x <> argInt y <> argInt width <> argInt height)

-- | Events delivered to a @wl_region@.
data WlRegionEvent
  = WlRegionUnknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @wl_region@ object.
wlRegionListen :: Connection -> ObjectId -> (WlRegionEvent -> IO ()) -> IO ()
wlRegionListen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (WlRegionUnknown opcode body)

