-- | Bindings for @river-input-management-v1.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.InputManagement
  (
    RiverInputManagerV1Event(..)
  , riverInputManagerV1Interface
  , riverInputManagerV1Version
  , riverInputManagerV1Listen
  , riverInputManagerV1Stop
  , riverInputManagerV1Destroy
  , riverInputManagerV1CreateSeat
  , riverInputManagerV1DestroySeat
  , riverInputManagerV1ErrorInvalidDestroy
  , RiverInputDeviceV1Event(..)
  , riverInputDeviceV1Interface
  , riverInputDeviceV1Version
  , riverInputDeviceV1Listen
  , riverInputDeviceV1Destroy
  , riverInputDeviceV1AssignToSeat
  , riverInputDeviceV1SetRepeatInfo
  , riverInputDeviceV1SetScrollFactor
  , riverInputDeviceV1MapToOutput
  , riverInputDeviceV1MapToRectangle
  , riverInputDeviceV1ErrorInvalidRepeatInfo
  , riverInputDeviceV1ErrorInvalidScrollFactor
  , riverInputDeviceV1ErrorInvalidMapToRectangle
  , riverInputDeviceV1TypeKeyboard
  , riverInputDeviceV1TypePointer
  , riverInputDeviceV1TypeTouch
  , riverInputDeviceV1TypeTablet
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_input_manager_v1 (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverInputManagerV1Interface :: ByteString
riverInputManagerV1Interface = "river_input_manager_v1"

-- | The highest version these bindings were generated against.
riverInputManagerV1Version :: Word32
riverInputManagerV1Version = 2

-- | @river_input_manager_v1.error.invalid_destroy@
riverInputManagerV1ErrorInvalidDestroy :: Word32
riverInputManagerV1ErrorInvalidDestroy = 0

-- | @river_input_manager_v1.stop@
riverInputManagerV1Stop :: Connection -> ObjectId -> IO ()
riverInputManagerV1Stop conn self =
  request conn self 0 (mempty)

-- | @river_input_manager_v1.destroy@
riverInputManagerV1Destroy :: Connection -> ObjectId -> IO ()
riverInputManagerV1Destroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | @river_input_manager_v1.create_seat@
riverInputManagerV1CreateSeat :: Connection -> ObjectId -> ByteString -> IO ()
riverInputManagerV1CreateSeat conn self name =
  request conn self 2 (argString (Just name))

-- | @river_input_manager_v1.destroy_seat@
riverInputManagerV1DestroySeat :: Connection -> ObjectId -> ByteString -> IO ()
riverInputManagerV1DestroySeat conn self name =
  request conn self 3 (argString (Just name))

-- | Events delivered to a @river_input_manager_v1@.
data RiverInputManagerV1Event
  = RiverInputManagerV1Finished
  | RiverInputManagerV1InputDevice !ObjectId
  | RiverInputManagerV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_input_manager_v1@ object.
riverInputManagerV1Listen :: Connection -> ObjectId -> (RiverInputManagerV1Event -> IO ()) -> IO ()
riverInputManagerV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverInputManagerV1Finished
    1 ->
      handler =<< decode (RiverInputManagerV1InputDevice <$> getObject) body
    _ -> handler (RiverInputManagerV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_input_device_v1 (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverInputDeviceV1Interface :: ByteString
riverInputDeviceV1Interface = "river_input_device_v1"

-- | The highest version these bindings were generated against.
riverInputDeviceV1Version :: Word32
riverInputDeviceV1Version = 2

-- | @river_input_device_v1.error.invalid_repeat_info@
riverInputDeviceV1ErrorInvalidRepeatInfo :: Word32
riverInputDeviceV1ErrorInvalidRepeatInfo = 0

-- | @river_input_device_v1.error.invalid_scroll_factor@
riverInputDeviceV1ErrorInvalidScrollFactor :: Word32
riverInputDeviceV1ErrorInvalidScrollFactor = 1

-- | @river_input_device_v1.error.invalid_map_to_rectangle@
riverInputDeviceV1ErrorInvalidMapToRectangle :: Word32
riverInputDeviceV1ErrorInvalidMapToRectangle = 2

-- | @river_input_device_v1.type.keyboard@
riverInputDeviceV1TypeKeyboard :: Word32
riverInputDeviceV1TypeKeyboard = 0

-- | @river_input_device_v1.type.pointer@
riverInputDeviceV1TypePointer :: Word32
riverInputDeviceV1TypePointer = 1

-- | @river_input_device_v1.type.touch@
riverInputDeviceV1TypeTouch :: Word32
riverInputDeviceV1TypeTouch = 2

-- | @river_input_device_v1.type.tablet@
riverInputDeviceV1TypeTablet :: Word32
riverInputDeviceV1TypeTablet = 3

-- | @river_input_device_v1.destroy@
riverInputDeviceV1Destroy :: Connection -> ObjectId -> IO ()
riverInputDeviceV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_input_device_v1.assign_to_seat@
riverInputDeviceV1AssignToSeat :: Connection -> ObjectId -> ByteString -> IO ()
riverInputDeviceV1AssignToSeat conn self name =
  request conn self 1 (argString (Just name))

-- | @river_input_device_v1.set_repeat_info@
riverInputDeviceV1SetRepeatInfo :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverInputDeviceV1SetRepeatInfo conn self rate delay =
  request conn self 2 (argInt rate <> argInt delay)

-- | @river_input_device_v1.set_scroll_factor@
riverInputDeviceV1SetScrollFactor :: Connection -> ObjectId -> Fixed -> IO ()
riverInputDeviceV1SetScrollFactor conn self factor =
  request conn self 3 (argFixed factor)

-- | @river_input_device_v1.map_to_output@
riverInputDeviceV1MapToOutput :: Connection -> ObjectId -> ObjectId -> IO ()
riverInputDeviceV1MapToOutput conn self output =
  request conn self 4 (argObject output)

-- | @river_input_device_v1.map_to_rectangle@
riverInputDeviceV1MapToRectangle :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
riverInputDeviceV1MapToRectangle conn self x y width height =
  request conn self 5 (argInt x <> argInt y <> argInt width <> argInt height)

-- | Events delivered to a @river_input_device_v1@.
data RiverInputDeviceV1Event
  = RiverInputDeviceV1Removed
  | RiverInputDeviceV1Type !Word32
  | RiverInputDeviceV1Name !ByteString
  | RiverInputDeviceV1Done
  | RiverInputDeviceV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_input_device_v1@ object.
riverInputDeviceV1Listen :: Connection -> ObjectId -> (RiverInputDeviceV1Event -> IO ()) -> IO ()
riverInputDeviceV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverInputDeviceV1Removed
    1 ->
      handler =<< decode (RiverInputDeviceV1Type <$> getWord32) body
    2 ->
      handler =<< decode (RiverInputDeviceV1Name <$> getString) body
    3 -> handler RiverInputDeviceV1Done
    _ -> handler (RiverInputDeviceV1Unknown opcode body)

