-- | Bindings for @wlr-layer-shell-unstable-v1.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.LayerShellClient
  (
    ZwlrLayerShellV1Event(..)
  , zwlrLayerShellV1Interface
  , zwlrLayerShellV1Version
  , zwlrLayerShellV1Listen
  , zwlrLayerShellV1GetLayerSurface
  , zwlrLayerShellV1Destroy
  , zwlrLayerShellV1ErrorRole
  , zwlrLayerShellV1ErrorInvalidLayer
  , zwlrLayerShellV1ErrorAlreadyConstructed
  , zwlrLayerShellV1LayerBackground
  , zwlrLayerShellV1LayerBottom
  , zwlrLayerShellV1LayerTop
  , zwlrLayerShellV1LayerOverlay
  , ZwlrLayerSurfaceV1Event(..)
  , zwlrLayerSurfaceV1Interface
  , zwlrLayerSurfaceV1Version
  , zwlrLayerSurfaceV1Listen
  , zwlrLayerSurfaceV1SetSize
  , zwlrLayerSurfaceV1SetAnchor
  , zwlrLayerSurfaceV1SetExclusiveZone
  , zwlrLayerSurfaceV1SetMargin
  , zwlrLayerSurfaceV1SetKeyboardInteractivity
  , zwlrLayerSurfaceV1GetPopup
  , zwlrLayerSurfaceV1AckConfigure
  , zwlrLayerSurfaceV1Destroy
  , zwlrLayerSurfaceV1SetLayer
  , zwlrLayerSurfaceV1SetExclusiveEdge
  , zwlrLayerSurfaceV1KeyboardInteractivityNone
  , zwlrLayerSurfaceV1KeyboardInteractivityExclusive
  , zwlrLayerSurfaceV1KeyboardInteractivityOnDemand
  , zwlrLayerSurfaceV1ErrorInvalidSurfaceState
  , zwlrLayerSurfaceV1ErrorInvalidSize
  , zwlrLayerSurfaceV1ErrorInvalidAnchor
  , zwlrLayerSurfaceV1ErrorInvalidKeyboardInteractivity
  , zwlrLayerSurfaceV1ErrorInvalidExclusiveEdge
  , zwlrLayerSurfaceV1AnchorTop
  , zwlrLayerSurfaceV1AnchorBottom
  , zwlrLayerSurfaceV1AnchorLeft
  , zwlrLayerSurfaceV1AnchorRight
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- zwlr_layer_shell_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
zwlrLayerShellV1Interface :: ByteString
zwlrLayerShellV1Interface = "zwlr_layer_shell_v1"

-- | The highest version these bindings were generated against.
zwlrLayerShellV1Version :: Word32
zwlrLayerShellV1Version = 5

-- | @zwlr_layer_shell_v1.error.role@
zwlrLayerShellV1ErrorRole :: Word32
zwlrLayerShellV1ErrorRole = 0

-- | @zwlr_layer_shell_v1.error.invalid_layer@
zwlrLayerShellV1ErrorInvalidLayer :: Word32
zwlrLayerShellV1ErrorInvalidLayer = 1

-- | @zwlr_layer_shell_v1.error.already_constructed@
zwlrLayerShellV1ErrorAlreadyConstructed :: Word32
zwlrLayerShellV1ErrorAlreadyConstructed = 2

-- | @zwlr_layer_shell_v1.layer.background@
zwlrLayerShellV1LayerBackground :: Word32
zwlrLayerShellV1LayerBackground = 0

-- | @zwlr_layer_shell_v1.layer.bottom@
zwlrLayerShellV1LayerBottom :: Word32
zwlrLayerShellV1LayerBottom = 1

-- | @zwlr_layer_shell_v1.layer.top@
zwlrLayerShellV1LayerTop :: Word32
zwlrLayerShellV1LayerTop = 2

-- | @zwlr_layer_shell_v1.layer.overlay@
zwlrLayerShellV1LayerOverlay :: Word32
zwlrLayerShellV1LayerOverlay = 3

-- | @zwlr_layer_shell_v1.get_layer_surface@
zwlrLayerShellV1GetLayerSurface :: Connection -> ObjectId -> ObjectId -> ObjectId -> Word32 -> ByteString -> IO ObjectId
zwlrLayerShellV1GetLayerSurface conn self surface output layer namespace =
  do
    id_ <- newObject conn
    request conn self 0 (argObject id_ <> argObject surface <> argObject output <> argUInt layer <> argString (Just namespace))
    pure id_

-- | @zwlr_layer_shell_v1.destroy@
-- Since version 3.
zwlrLayerShellV1Destroy :: Connection -> ObjectId -> IO ()
zwlrLayerShellV1Destroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | Events delivered to a @zwlr_layer_shell_v1@.
data ZwlrLayerShellV1Event
  = ZwlrLayerShellV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @zwlr_layer_shell_v1@ object.
zwlrLayerShellV1Listen :: Connection -> ObjectId -> (ZwlrLayerShellV1Event -> IO ()) -> IO ()
zwlrLayerShellV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (ZwlrLayerShellV1Unknown opcode body)

--------------------------------------------------------------------------------
-- zwlr_layer_surface_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
zwlrLayerSurfaceV1Interface :: ByteString
zwlrLayerSurfaceV1Interface = "zwlr_layer_surface_v1"

-- | The highest version these bindings were generated against.
zwlrLayerSurfaceV1Version :: Word32
zwlrLayerSurfaceV1Version = 5

-- | @zwlr_layer_surface_v1.keyboard_interactivity.none@
zwlrLayerSurfaceV1KeyboardInteractivityNone :: Word32
zwlrLayerSurfaceV1KeyboardInteractivityNone = 0

-- | @zwlr_layer_surface_v1.keyboard_interactivity.exclusive@
zwlrLayerSurfaceV1KeyboardInteractivityExclusive :: Word32
zwlrLayerSurfaceV1KeyboardInteractivityExclusive = 1

-- | @zwlr_layer_surface_v1.keyboard_interactivity.on_demand@
zwlrLayerSurfaceV1KeyboardInteractivityOnDemand :: Word32
zwlrLayerSurfaceV1KeyboardInteractivityOnDemand = 2

-- | @zwlr_layer_surface_v1.error.invalid_surface_state@
zwlrLayerSurfaceV1ErrorInvalidSurfaceState :: Word32
zwlrLayerSurfaceV1ErrorInvalidSurfaceState = 0

-- | @zwlr_layer_surface_v1.error.invalid_size@
zwlrLayerSurfaceV1ErrorInvalidSize :: Word32
zwlrLayerSurfaceV1ErrorInvalidSize = 1

-- | @zwlr_layer_surface_v1.error.invalid_anchor@
zwlrLayerSurfaceV1ErrorInvalidAnchor :: Word32
zwlrLayerSurfaceV1ErrorInvalidAnchor = 2

-- | @zwlr_layer_surface_v1.error.invalid_keyboard_interactivity@
zwlrLayerSurfaceV1ErrorInvalidKeyboardInteractivity :: Word32
zwlrLayerSurfaceV1ErrorInvalidKeyboardInteractivity = 3

-- | @zwlr_layer_surface_v1.error.invalid_exclusive_edge@
zwlrLayerSurfaceV1ErrorInvalidExclusiveEdge :: Word32
zwlrLayerSurfaceV1ErrorInvalidExclusiveEdge = 4

-- | @zwlr_layer_surface_v1.anchor.top@
zwlrLayerSurfaceV1AnchorTop :: Word32
zwlrLayerSurfaceV1AnchorTop = 1

-- | @zwlr_layer_surface_v1.anchor.bottom@
zwlrLayerSurfaceV1AnchorBottom :: Word32
zwlrLayerSurfaceV1AnchorBottom = 2

-- | @zwlr_layer_surface_v1.anchor.left@
zwlrLayerSurfaceV1AnchorLeft :: Word32
zwlrLayerSurfaceV1AnchorLeft = 4

-- | @zwlr_layer_surface_v1.anchor.right@
zwlrLayerSurfaceV1AnchorRight :: Word32
zwlrLayerSurfaceV1AnchorRight = 8

-- | @zwlr_layer_surface_v1.set_size@
zwlrLayerSurfaceV1SetSize :: Connection -> ObjectId -> Word32 -> Word32 -> IO ()
zwlrLayerSurfaceV1SetSize conn self width height =
  request conn self 0 (argUInt width <> argUInt height)

-- | @zwlr_layer_surface_v1.set_anchor@
zwlrLayerSurfaceV1SetAnchor :: Connection -> ObjectId -> Word32 -> IO ()
zwlrLayerSurfaceV1SetAnchor conn self anchor =
  request conn self 1 (argUInt anchor)

-- | @zwlr_layer_surface_v1.set_exclusive_zone@
zwlrLayerSurfaceV1SetExclusiveZone :: Connection -> ObjectId -> Int32 -> IO ()
zwlrLayerSurfaceV1SetExclusiveZone conn self zone =
  request conn self 2 (argInt zone)

-- | @zwlr_layer_surface_v1.set_margin@
zwlrLayerSurfaceV1SetMargin :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
zwlrLayerSurfaceV1SetMargin conn self top right bottom left =
  request conn self 3 (argInt top <> argInt right <> argInt bottom <> argInt left)

-- | @zwlr_layer_surface_v1.set_keyboard_interactivity@
zwlrLayerSurfaceV1SetKeyboardInteractivity :: Connection -> ObjectId -> Word32 -> IO ()
zwlrLayerSurfaceV1SetKeyboardInteractivity conn self keyboardInteractivity =
  request conn self 4 (argUInt keyboardInteractivity)

-- | @zwlr_layer_surface_v1.get_popup@
zwlrLayerSurfaceV1GetPopup :: Connection -> ObjectId -> ObjectId -> IO ()
zwlrLayerSurfaceV1GetPopup conn self popup =
  request conn self 5 (argObject popup)

-- | @zwlr_layer_surface_v1.ack_configure@
zwlrLayerSurfaceV1AckConfigure :: Connection -> ObjectId -> Word32 -> IO ()
zwlrLayerSurfaceV1AckConfigure conn self serial =
  request conn self 6 (argUInt serial)

-- | @zwlr_layer_surface_v1.destroy@
zwlrLayerSurfaceV1Destroy :: Connection -> ObjectId -> IO ()
zwlrLayerSurfaceV1Destroy conn self =
  request conn self 7 (mempty)
    >> freeObject conn self

-- | @zwlr_layer_surface_v1.set_layer@
-- Since version 2.
zwlrLayerSurfaceV1SetLayer :: Connection -> ObjectId -> Word32 -> IO ()
zwlrLayerSurfaceV1SetLayer conn self layer =
  request conn self 8 (argUInt layer)

-- | @zwlr_layer_surface_v1.set_exclusive_edge@
-- Since version 5.
zwlrLayerSurfaceV1SetExclusiveEdge :: Connection -> ObjectId -> Word32 -> IO ()
zwlrLayerSurfaceV1SetExclusiveEdge conn self edge =
  request conn self 9 (argUInt edge)

-- | Events delivered to a @zwlr_layer_surface_v1@.
data ZwlrLayerSurfaceV1Event
  = ZwlrLayerSurfaceV1Configure !Word32 !Word32 !Word32
  | ZwlrLayerSurfaceV1Closed
  | ZwlrLayerSurfaceV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @zwlr_layer_surface_v1@ object.
zwlrLayerSurfaceV1Listen :: Connection -> ObjectId -> (ZwlrLayerSurfaceV1Event -> IO ()) -> IO ()
zwlrLayerSurfaceV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (ZwlrLayerSurfaceV1Configure <$> getWord32 <*> getWord32 <*> getWord32) body
    1 -> handler ZwlrLayerSurfaceV1Closed
    _ -> handler (ZwlrLayerSurfaceV1Unknown opcode body)

