-- | Bindings for @river-libinput-config-v1.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.LibinputConfig
  (
    RiverLibinputConfigV1Event(..)
  , riverLibinputConfigV1Interface
  , riverLibinputConfigV1Version
  , riverLibinputConfigV1Listen
  , riverLibinputConfigV1Stop
  , riverLibinputConfigV1Destroy
  , riverLibinputConfigV1CreateAccelConfig
  , riverLibinputConfigV1ErrorInvalidArg
  , riverLibinputConfigV1ErrorInvalidDestroy
  , RiverLibinputDeviceV1Event(..)
  , riverLibinputDeviceV1Interface
  , riverLibinputDeviceV1Version
  , riverLibinputDeviceV1Listen
  , riverLibinputDeviceV1Destroy
  , riverLibinputDeviceV1SetSendEvents
  , riverLibinputDeviceV1SetTap
  , riverLibinputDeviceV1SetTapButtonMap
  , riverLibinputDeviceV1SetDrag
  , riverLibinputDeviceV1SetDragLock
  , riverLibinputDeviceV1SetThreeFingerDrag
  , riverLibinputDeviceV1SetCalibrationMatrix
  , riverLibinputDeviceV1SetAccelProfile
  , riverLibinputDeviceV1SetAccelSpeed
  , riverLibinputDeviceV1ApplyAccelConfig
  , riverLibinputDeviceV1SetNaturalScroll
  , riverLibinputDeviceV1SetLeftHanded
  , riverLibinputDeviceV1SetClickMethod
  , riverLibinputDeviceV1SetClickfingerButtonMap
  , riverLibinputDeviceV1SetMiddleEmulation
  , riverLibinputDeviceV1SetScrollMethod
  , riverLibinputDeviceV1SetScrollButton
  , riverLibinputDeviceV1SetScrollButtonLock
  , riverLibinputDeviceV1SetDwt
  , riverLibinputDeviceV1SetDwtp
  , riverLibinputDeviceV1SetRotation
  , riverLibinputDeviceV1ErrorInvalidArg
  , riverLibinputDeviceV1SendEventsModesEnabled
  , riverLibinputDeviceV1SendEventsModesDisabled
  , riverLibinputDeviceV1SendEventsModesDisabledOnExternalMouse
  , riverLibinputDeviceV1TapStateDisabled
  , riverLibinputDeviceV1TapStateEnabled
  , riverLibinputDeviceV1TapButtonMapLrm
  , riverLibinputDeviceV1TapButtonMapLmr
  , riverLibinputDeviceV1DragStateDisabled
  , riverLibinputDeviceV1DragStateEnabled
  , riverLibinputDeviceV1DragLockStateDisabled
  , riverLibinputDeviceV1DragLockStateEnabledTimeout
  , riverLibinputDeviceV1DragLockStateEnabledSticky
  , riverLibinputDeviceV1ThreeFingerDragStateDisabled
  , riverLibinputDeviceV1ThreeFingerDragStateEnabled3fg
  , riverLibinputDeviceV1ThreeFingerDragStateEnabled4fg
  , riverLibinputDeviceV1AccelProfileNone
  , riverLibinputDeviceV1AccelProfileFlat
  , riverLibinputDeviceV1AccelProfileAdaptive
  , riverLibinputDeviceV1AccelProfileCustom
  , riverLibinputDeviceV1AccelProfilesNone
  , riverLibinputDeviceV1AccelProfilesFlat
  , riverLibinputDeviceV1AccelProfilesAdaptive
  , riverLibinputDeviceV1AccelProfilesCustom
  , riverLibinputDeviceV1NaturalScrollStateDisabled
  , riverLibinputDeviceV1NaturalScrollStateEnabled
  , riverLibinputDeviceV1LeftHandedStateDisabled
  , riverLibinputDeviceV1LeftHandedStateEnabled
  , riverLibinputDeviceV1ClickMethodNone
  , riverLibinputDeviceV1ClickMethodButtonAreas
  , riverLibinputDeviceV1ClickMethodClickfinger
  , riverLibinputDeviceV1ClickMethodsNone
  , riverLibinputDeviceV1ClickMethodsButtonAreas
  , riverLibinputDeviceV1ClickMethodsClickfinger
  , riverLibinputDeviceV1ClickfingerButtonMapLrm
  , riverLibinputDeviceV1ClickfingerButtonMapLmr
  , riverLibinputDeviceV1MiddleEmulationStateDisabled
  , riverLibinputDeviceV1MiddleEmulationStateEnabled
  , riverLibinputDeviceV1ScrollMethodNoScroll
  , riverLibinputDeviceV1ScrollMethodTwoFinger
  , riverLibinputDeviceV1ScrollMethodEdge
  , riverLibinputDeviceV1ScrollMethodOnButtonDown
  , riverLibinputDeviceV1ScrollMethodsNoScroll
  , riverLibinputDeviceV1ScrollMethodsTwoFinger
  , riverLibinputDeviceV1ScrollMethodsEdge
  , riverLibinputDeviceV1ScrollMethodsOnButtonDown
  , riverLibinputDeviceV1ScrollButtonLockStateDisabled
  , riverLibinputDeviceV1ScrollButtonLockStateEnabled
  , riverLibinputDeviceV1DwtStateDisabled
  , riverLibinputDeviceV1DwtStateEnabled
  , riverLibinputDeviceV1DwtpStateDisabled
  , riverLibinputDeviceV1DwtpStateEnabled
  , RiverLibinputAccelConfigV1Event(..)
  , riverLibinputAccelConfigV1Interface
  , riverLibinputAccelConfigV1Version
  , riverLibinputAccelConfigV1Listen
  , riverLibinputAccelConfigV1Destroy
  , riverLibinputAccelConfigV1SetPoints
  , riverLibinputAccelConfigV1ErrorInvalidArg
  , riverLibinputAccelConfigV1AccelTypeFallback
  , riverLibinputAccelConfigV1AccelTypeMotion
  , riverLibinputAccelConfigV1AccelTypeScroll
  , RiverLibinputResultV1Event(..)
  , riverLibinputResultV1Interface
  , riverLibinputResultV1Version
  , riverLibinputResultV1Listen
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_libinput_config_v1 (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLibinputConfigV1Interface :: ByteString
riverLibinputConfigV1Interface = "river_libinput_config_v1"

-- | The highest version these bindings were generated against.
riverLibinputConfigV1Version :: Word32
riverLibinputConfigV1Version = 2

-- | @river_libinput_config_v1.error.invalid_arg@
riverLibinputConfigV1ErrorInvalidArg :: Word32
riverLibinputConfigV1ErrorInvalidArg = 0

-- | @river_libinput_config_v1.error.invalid_destroy@
riverLibinputConfigV1ErrorInvalidDestroy :: Word32
riverLibinputConfigV1ErrorInvalidDestroy = 1

-- | @river_libinput_config_v1.stop@
riverLibinputConfigV1Stop :: Connection -> ObjectId -> IO ()
riverLibinputConfigV1Stop conn self =
  request conn self 0 (mempty)

-- | @river_libinput_config_v1.destroy@
riverLibinputConfigV1Destroy :: Connection -> ObjectId -> IO ()
riverLibinputConfigV1Destroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | @river_libinput_config_v1.create_accel_config@
riverLibinputConfigV1CreateAccelConfig :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputConfigV1CreateAccelConfig conn self profile =
  requestNew conn self 2 (\id_ -> argObject id_ <> argUInt profile)

-- | Events delivered to a @river_libinput_config_v1@.
data RiverLibinputConfigV1Event
  = RiverLibinputConfigV1Finished
  | RiverLibinputConfigV1LibinputDevice !ObjectId
  | RiverLibinputConfigV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_libinput_config_v1@ object.
riverLibinputConfigV1Listen :: Connection -> ObjectId -> (RiverLibinputConfigV1Event -> IO ()) -> IO ()
riverLibinputConfigV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverLibinputConfigV1Finished
    1 ->
      handler =<< decode (RiverLibinputConfigV1LibinputDevice <$> getObject) body
    _ -> handler (RiverLibinputConfigV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_libinput_device_v1 (version 2)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLibinputDeviceV1Interface :: ByteString
riverLibinputDeviceV1Interface = "river_libinput_device_v1"

-- | The highest version these bindings were generated against.
riverLibinputDeviceV1Version :: Word32
riverLibinputDeviceV1Version = 2

-- | @river_libinput_device_v1.error.invalid_arg@
riverLibinputDeviceV1ErrorInvalidArg :: Word32
riverLibinputDeviceV1ErrorInvalidArg = 0

-- | @river_libinput_device_v1.send_events_modes.enabled@
riverLibinputDeviceV1SendEventsModesEnabled :: Word32
riverLibinputDeviceV1SendEventsModesEnabled = 0

-- | @river_libinput_device_v1.send_events_modes.disabled@
riverLibinputDeviceV1SendEventsModesDisabled :: Word32
riverLibinputDeviceV1SendEventsModesDisabled = 1

-- | @river_libinput_device_v1.send_events_modes.disabled_on_external_mouse@
riverLibinputDeviceV1SendEventsModesDisabledOnExternalMouse :: Word32
riverLibinputDeviceV1SendEventsModesDisabledOnExternalMouse = 2

-- | @river_libinput_device_v1.tap_state.disabled@
riverLibinputDeviceV1TapStateDisabled :: Word32
riverLibinputDeviceV1TapStateDisabled = 0

-- | @river_libinput_device_v1.tap_state.enabled@
riverLibinputDeviceV1TapStateEnabled :: Word32
riverLibinputDeviceV1TapStateEnabled = 1

-- | @river_libinput_device_v1.tap_button_map.lrm@
riverLibinputDeviceV1TapButtonMapLrm :: Word32
riverLibinputDeviceV1TapButtonMapLrm = 0

-- | @river_libinput_device_v1.tap_button_map.lmr@
riverLibinputDeviceV1TapButtonMapLmr :: Word32
riverLibinputDeviceV1TapButtonMapLmr = 1

-- | @river_libinput_device_v1.drag_state.disabled@
riverLibinputDeviceV1DragStateDisabled :: Word32
riverLibinputDeviceV1DragStateDisabled = 0

-- | @river_libinput_device_v1.drag_state.enabled@
riverLibinputDeviceV1DragStateEnabled :: Word32
riverLibinputDeviceV1DragStateEnabled = 1

-- | @river_libinput_device_v1.drag_lock_state.disabled@
riverLibinputDeviceV1DragLockStateDisabled :: Word32
riverLibinputDeviceV1DragLockStateDisabled = 0

-- | @river_libinput_device_v1.drag_lock_state.enabled_timeout@
riverLibinputDeviceV1DragLockStateEnabledTimeout :: Word32
riverLibinputDeviceV1DragLockStateEnabledTimeout = 1

-- | @river_libinput_device_v1.drag_lock_state.enabled_sticky@
riverLibinputDeviceV1DragLockStateEnabledSticky :: Word32
riverLibinputDeviceV1DragLockStateEnabledSticky = 2

-- | @river_libinput_device_v1.three_finger_drag_state.disabled@
riverLibinputDeviceV1ThreeFingerDragStateDisabled :: Word32
riverLibinputDeviceV1ThreeFingerDragStateDisabled = 0

-- | @river_libinput_device_v1.three_finger_drag_state.enabled_3fg@
riverLibinputDeviceV1ThreeFingerDragStateEnabled3fg :: Word32
riverLibinputDeviceV1ThreeFingerDragStateEnabled3fg = 1

-- | @river_libinput_device_v1.three_finger_drag_state.enabled_4fg@
riverLibinputDeviceV1ThreeFingerDragStateEnabled4fg :: Word32
riverLibinputDeviceV1ThreeFingerDragStateEnabled4fg = 2

-- | @river_libinput_device_v1.accel_profile.none@
riverLibinputDeviceV1AccelProfileNone :: Word32
riverLibinputDeviceV1AccelProfileNone = 0

-- | @river_libinput_device_v1.accel_profile.flat@
riverLibinputDeviceV1AccelProfileFlat :: Word32
riverLibinputDeviceV1AccelProfileFlat = 1

-- | @river_libinput_device_v1.accel_profile.adaptive@
riverLibinputDeviceV1AccelProfileAdaptive :: Word32
riverLibinputDeviceV1AccelProfileAdaptive = 2

-- | @river_libinput_device_v1.accel_profile.custom@
riverLibinputDeviceV1AccelProfileCustom :: Word32
riverLibinputDeviceV1AccelProfileCustom = 4

-- | @river_libinput_device_v1.accel_profiles.none@
riverLibinputDeviceV1AccelProfilesNone :: Word32
riverLibinputDeviceV1AccelProfilesNone = 0

-- | @river_libinput_device_v1.accel_profiles.flat@
riverLibinputDeviceV1AccelProfilesFlat :: Word32
riverLibinputDeviceV1AccelProfilesFlat = 1

-- | @river_libinput_device_v1.accel_profiles.adaptive@
riverLibinputDeviceV1AccelProfilesAdaptive :: Word32
riverLibinputDeviceV1AccelProfilesAdaptive = 2

-- | @river_libinput_device_v1.accel_profiles.custom@
riverLibinputDeviceV1AccelProfilesCustom :: Word32
riverLibinputDeviceV1AccelProfilesCustom = 4

-- | @river_libinput_device_v1.natural_scroll_state.disabled@
riverLibinputDeviceV1NaturalScrollStateDisabled :: Word32
riverLibinputDeviceV1NaturalScrollStateDisabled = 0

-- | @river_libinput_device_v1.natural_scroll_state.enabled@
riverLibinputDeviceV1NaturalScrollStateEnabled :: Word32
riverLibinputDeviceV1NaturalScrollStateEnabled = 1

-- | @river_libinput_device_v1.left_handed_state.disabled@
riverLibinputDeviceV1LeftHandedStateDisabled :: Word32
riverLibinputDeviceV1LeftHandedStateDisabled = 0

-- | @river_libinput_device_v1.left_handed_state.enabled@
riverLibinputDeviceV1LeftHandedStateEnabled :: Word32
riverLibinputDeviceV1LeftHandedStateEnabled = 1

-- | @river_libinput_device_v1.click_method.none@
riverLibinputDeviceV1ClickMethodNone :: Word32
riverLibinputDeviceV1ClickMethodNone = 0

-- | @river_libinput_device_v1.click_method.button_areas@
riverLibinputDeviceV1ClickMethodButtonAreas :: Word32
riverLibinputDeviceV1ClickMethodButtonAreas = 1

-- | @river_libinput_device_v1.click_method.clickfinger@
riverLibinputDeviceV1ClickMethodClickfinger :: Word32
riverLibinputDeviceV1ClickMethodClickfinger = 2

-- | @river_libinput_device_v1.click_methods.none@
riverLibinputDeviceV1ClickMethodsNone :: Word32
riverLibinputDeviceV1ClickMethodsNone = 0

-- | @river_libinput_device_v1.click_methods.button_areas@
riverLibinputDeviceV1ClickMethodsButtonAreas :: Word32
riverLibinputDeviceV1ClickMethodsButtonAreas = 1

-- | @river_libinput_device_v1.click_methods.clickfinger@
riverLibinputDeviceV1ClickMethodsClickfinger :: Word32
riverLibinputDeviceV1ClickMethodsClickfinger = 2

-- | @river_libinput_device_v1.clickfinger_button_map.lrm@
riverLibinputDeviceV1ClickfingerButtonMapLrm :: Word32
riverLibinputDeviceV1ClickfingerButtonMapLrm = 0

-- | @river_libinput_device_v1.clickfinger_button_map.lmr@
riverLibinputDeviceV1ClickfingerButtonMapLmr :: Word32
riverLibinputDeviceV1ClickfingerButtonMapLmr = 1

-- | @river_libinput_device_v1.middle_emulation_state.disabled@
riverLibinputDeviceV1MiddleEmulationStateDisabled :: Word32
riverLibinputDeviceV1MiddleEmulationStateDisabled = 0

-- | @river_libinput_device_v1.middle_emulation_state.enabled@
riverLibinputDeviceV1MiddleEmulationStateEnabled :: Word32
riverLibinputDeviceV1MiddleEmulationStateEnabled = 1

-- | @river_libinput_device_v1.scroll_method.no_scroll@
riverLibinputDeviceV1ScrollMethodNoScroll :: Word32
riverLibinputDeviceV1ScrollMethodNoScroll = 0

-- | @river_libinput_device_v1.scroll_method.two_finger@
riverLibinputDeviceV1ScrollMethodTwoFinger :: Word32
riverLibinputDeviceV1ScrollMethodTwoFinger = 1

-- | @river_libinput_device_v1.scroll_method.edge@
riverLibinputDeviceV1ScrollMethodEdge :: Word32
riverLibinputDeviceV1ScrollMethodEdge = 2

-- | @river_libinput_device_v1.scroll_method.on_button_down@
riverLibinputDeviceV1ScrollMethodOnButtonDown :: Word32
riverLibinputDeviceV1ScrollMethodOnButtonDown = 4

-- | @river_libinput_device_v1.scroll_methods.no_scroll@
riverLibinputDeviceV1ScrollMethodsNoScroll :: Word32
riverLibinputDeviceV1ScrollMethodsNoScroll = 0

-- | @river_libinput_device_v1.scroll_methods.two_finger@
riverLibinputDeviceV1ScrollMethodsTwoFinger :: Word32
riverLibinputDeviceV1ScrollMethodsTwoFinger = 1

-- | @river_libinput_device_v1.scroll_methods.edge@
riverLibinputDeviceV1ScrollMethodsEdge :: Word32
riverLibinputDeviceV1ScrollMethodsEdge = 2

-- | @river_libinput_device_v1.scroll_methods.on_button_down@
riverLibinputDeviceV1ScrollMethodsOnButtonDown :: Word32
riverLibinputDeviceV1ScrollMethodsOnButtonDown = 4

-- | @river_libinput_device_v1.scroll_button_lock_state.disabled@
riverLibinputDeviceV1ScrollButtonLockStateDisabled :: Word32
riverLibinputDeviceV1ScrollButtonLockStateDisabled = 0

-- | @river_libinput_device_v1.scroll_button_lock_state.enabled@
riverLibinputDeviceV1ScrollButtonLockStateEnabled :: Word32
riverLibinputDeviceV1ScrollButtonLockStateEnabled = 1

-- | @river_libinput_device_v1.dwt_state.disabled@
riverLibinputDeviceV1DwtStateDisabled :: Word32
riverLibinputDeviceV1DwtStateDisabled = 0

-- | @river_libinput_device_v1.dwt_state.enabled@
riverLibinputDeviceV1DwtStateEnabled :: Word32
riverLibinputDeviceV1DwtStateEnabled = 1

-- | @river_libinput_device_v1.dwtp_state.disabled@
riverLibinputDeviceV1DwtpStateDisabled :: Word32
riverLibinputDeviceV1DwtpStateDisabled = 0

-- | @river_libinput_device_v1.dwtp_state.enabled@
riverLibinputDeviceV1DwtpStateEnabled :: Word32
riverLibinputDeviceV1DwtpStateEnabled = 1

-- | @river_libinput_device_v1.destroy@
riverLibinputDeviceV1Destroy :: Connection -> ObjectId -> IO ()
riverLibinputDeviceV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_libinput_device_v1.set_send_events@
riverLibinputDeviceV1SetSendEvents :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetSendEvents conn self mode =
  requestNew conn self 1 (\result -> argObject result <> argUInt mode)

-- | @river_libinput_device_v1.set_tap@
riverLibinputDeviceV1SetTap :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetTap conn self state =
  requestNew conn self 2 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_tap_button_map@
riverLibinputDeviceV1SetTapButtonMap :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetTapButtonMap conn self buttonMap =
  requestNew conn self 3 (\result -> argObject result <> argUInt buttonMap)

-- | @river_libinput_device_v1.set_drag@
riverLibinputDeviceV1SetDrag :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetDrag conn self state =
  requestNew conn self 4 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_drag_lock@
riverLibinputDeviceV1SetDragLock :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetDragLock conn self state =
  requestNew conn self 5 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_three_finger_drag@
riverLibinputDeviceV1SetThreeFingerDrag :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetThreeFingerDrag conn self state =
  requestNew conn self 6 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_calibration_matrix@
riverLibinputDeviceV1SetCalibrationMatrix :: Connection -> ObjectId -> ByteString -> IO ObjectId
riverLibinputDeviceV1SetCalibrationMatrix conn self matrix =
  requestNew conn self 7 (\result -> argObject result <> argArray matrix)

-- | @river_libinput_device_v1.set_accel_profile@
riverLibinputDeviceV1SetAccelProfile :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetAccelProfile conn self profile =
  requestNew conn self 8 (\result -> argObject result <> argUInt profile)

-- | @river_libinput_device_v1.set_accel_speed@
riverLibinputDeviceV1SetAccelSpeed :: Connection -> ObjectId -> ByteString -> IO ObjectId
riverLibinputDeviceV1SetAccelSpeed conn self speed =
  requestNew conn self 9 (\result -> argObject result <> argArray speed)

-- | @river_libinput_device_v1.apply_accel_config@
riverLibinputDeviceV1ApplyAccelConfig :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverLibinputDeviceV1ApplyAccelConfig conn self config =
  requestNew conn self 10 (\result -> argObject result <> argObject config)

-- | @river_libinput_device_v1.set_natural_scroll@
riverLibinputDeviceV1SetNaturalScroll :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetNaturalScroll conn self state =
  requestNew conn self 11 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_left_handed@
riverLibinputDeviceV1SetLeftHanded :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetLeftHanded conn self state =
  requestNew conn self 12 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_click_method@
riverLibinputDeviceV1SetClickMethod :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetClickMethod conn self method =
  requestNew conn self 13 (\result -> argObject result <> argUInt method)

-- | @river_libinput_device_v1.set_clickfinger_button_map@
riverLibinputDeviceV1SetClickfingerButtonMap :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetClickfingerButtonMap conn self buttonMap =
  requestNew conn self 14 (\result -> argObject result <> argUInt buttonMap)

-- | @river_libinput_device_v1.set_middle_emulation@
riverLibinputDeviceV1SetMiddleEmulation :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetMiddleEmulation conn self state =
  requestNew conn self 15 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_scroll_method@
riverLibinputDeviceV1SetScrollMethod :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetScrollMethod conn self method =
  requestNew conn self 16 (\result -> argObject result <> argUInt method)

-- | @river_libinput_device_v1.set_scroll_button@
riverLibinputDeviceV1SetScrollButton :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetScrollButton conn self button =
  requestNew conn self 17 (\result -> argObject result <> argUInt button)

-- | @river_libinput_device_v1.set_scroll_button_lock@
riverLibinputDeviceV1SetScrollButtonLock :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetScrollButtonLock conn self state =
  requestNew conn self 18 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_dwt@
riverLibinputDeviceV1SetDwt :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetDwt conn self state =
  requestNew conn self 19 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_dwtp@
riverLibinputDeviceV1SetDwtp :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetDwtp conn self state =
  requestNew conn self 20 (\result -> argObject result <> argUInt state)

-- | @river_libinput_device_v1.set_rotation@
riverLibinputDeviceV1SetRotation :: Connection -> ObjectId -> Word32 -> IO ObjectId
riverLibinputDeviceV1SetRotation conn self angle =
  requestNew conn self 21 (\result -> argObject result <> argUInt angle)

-- | Events delivered to a @river_libinput_device_v1@.
data RiverLibinputDeviceV1Event
  = RiverLibinputDeviceV1Removed
  | RiverLibinputDeviceV1InputDevice !ObjectId
  | RiverLibinputDeviceV1SendEventsSupport !Word32
  | RiverLibinputDeviceV1SendEventsDefault !Word32
  | RiverLibinputDeviceV1SendEventsCurrent !Word32
  | RiverLibinputDeviceV1TapSupport !Int32
  | RiverLibinputDeviceV1TapDefault !Word32
  | RiverLibinputDeviceV1TapCurrent !Word32
  | RiverLibinputDeviceV1TapButtonMapDefault !Word32
  | RiverLibinputDeviceV1TapButtonMapCurrent !Word32
  | RiverLibinputDeviceV1DragDefault !Word32
  | RiverLibinputDeviceV1DragCurrent !Word32
  | RiverLibinputDeviceV1DragLockDefault !Word32
  | RiverLibinputDeviceV1DragLockCurrent !Word32
  | RiverLibinputDeviceV1ThreeFingerDragSupport !Int32
  | RiverLibinputDeviceV1ThreeFingerDragDefault !Word32
  | RiverLibinputDeviceV1ThreeFingerDragCurrent !Word32
  | RiverLibinputDeviceV1CalibrationMatrixSupport !Int32
  | RiverLibinputDeviceV1CalibrationMatrixDefault !ByteString
  | RiverLibinputDeviceV1CalibrationMatrixCurrent !ByteString
  | RiverLibinputDeviceV1AccelProfilesSupport !Word32
  | RiverLibinputDeviceV1AccelProfileDefault !Word32
  | RiverLibinputDeviceV1AccelProfileCurrent !Word32
  | RiverLibinputDeviceV1AccelSpeedDefault !ByteString
  | RiverLibinputDeviceV1AccelSpeedCurrent !ByteString
  | RiverLibinputDeviceV1NaturalScrollSupport !Int32
  | RiverLibinputDeviceV1NaturalScrollDefault !Word32
  | RiverLibinputDeviceV1NaturalScrollCurrent !Word32
  | RiverLibinputDeviceV1LeftHandedSupport !Int32
  | RiverLibinputDeviceV1LeftHandedDefault !Word32
  | RiverLibinputDeviceV1LeftHandedCurrent !Word32
  | RiverLibinputDeviceV1ClickMethodSupport !Word32
  | RiverLibinputDeviceV1ClickMethodDefault !Word32
  | RiverLibinputDeviceV1ClickMethodCurrent !Word32
  | RiverLibinputDeviceV1ClickfingerButtonMapDefault !Word32
  | RiverLibinputDeviceV1ClickfingerButtonMapCurrent !Word32
  | RiverLibinputDeviceV1MiddleEmulationSupport !Int32
  | RiverLibinputDeviceV1MiddleEmulationDefault !Word32
  | RiverLibinputDeviceV1MiddleEmulationCurrent !Word32
  | RiverLibinputDeviceV1ScrollMethodSupport !Word32
  | RiverLibinputDeviceV1ScrollMethodDefault !Word32
  | RiverLibinputDeviceV1ScrollMethodCurrent !Word32
  | RiverLibinputDeviceV1ScrollButtonDefault !Word32
  | RiverLibinputDeviceV1ScrollButtonCurrent !Word32
  | RiverLibinputDeviceV1ScrollButtonLockDefault !Word32
  | RiverLibinputDeviceV1ScrollButtonLockCurrent !Word32
  | RiverLibinputDeviceV1DwtSupport !Int32
  | RiverLibinputDeviceV1DwtDefault !Word32
  | RiverLibinputDeviceV1DwtCurrent !Word32
  | RiverLibinputDeviceV1DwtpSupport !Int32
  | RiverLibinputDeviceV1DwtpDefault !Word32
  | RiverLibinputDeviceV1DwtpCurrent !Word32
  | RiverLibinputDeviceV1RotationSupport !Int32
  | RiverLibinputDeviceV1RotationDefault !Word32
  | RiverLibinputDeviceV1RotationCurrent !Word32
  | RiverLibinputDeviceV1Done
  | RiverLibinputDeviceV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_libinput_device_v1@ object.
riverLibinputDeviceV1Listen :: Connection -> ObjectId -> (RiverLibinputDeviceV1Event -> IO ()) -> IO ()
riverLibinputDeviceV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverLibinputDeviceV1Removed
    1 ->
      handler =<< decode (RiverLibinputDeviceV1InputDevice <$> getObject) body
    2 ->
      handler =<< decode (RiverLibinputDeviceV1SendEventsSupport <$> getWord32) body
    3 ->
      handler =<< decode (RiverLibinputDeviceV1SendEventsDefault <$> getWord32) body
    4 ->
      handler =<< decode (RiverLibinputDeviceV1SendEventsCurrent <$> getWord32) body
    5 ->
      handler =<< decode (RiverLibinputDeviceV1TapSupport <$> getInt) body
    6 ->
      handler =<< decode (RiverLibinputDeviceV1TapDefault <$> getWord32) body
    7 ->
      handler =<< decode (RiverLibinputDeviceV1TapCurrent <$> getWord32) body
    8 ->
      handler =<< decode (RiverLibinputDeviceV1TapButtonMapDefault <$> getWord32) body
    9 ->
      handler =<< decode (RiverLibinputDeviceV1TapButtonMapCurrent <$> getWord32) body
    10 ->
      handler =<< decode (RiverLibinputDeviceV1DragDefault <$> getWord32) body
    11 ->
      handler =<< decode (RiverLibinputDeviceV1DragCurrent <$> getWord32) body
    12 ->
      handler =<< decode (RiverLibinputDeviceV1DragLockDefault <$> getWord32) body
    13 ->
      handler =<< decode (RiverLibinputDeviceV1DragLockCurrent <$> getWord32) body
    14 ->
      handler =<< decode (RiverLibinputDeviceV1ThreeFingerDragSupport <$> getInt) body
    15 ->
      handler =<< decode (RiverLibinputDeviceV1ThreeFingerDragDefault <$> getWord32) body
    16 ->
      handler =<< decode (RiverLibinputDeviceV1ThreeFingerDragCurrent <$> getWord32) body
    17 ->
      handler =<< decode (RiverLibinputDeviceV1CalibrationMatrixSupport <$> getInt) body
    18 ->
      handler =<< decode (RiverLibinputDeviceV1CalibrationMatrixDefault <$> getArray) body
    19 ->
      handler =<< decode (RiverLibinputDeviceV1CalibrationMatrixCurrent <$> getArray) body
    20 ->
      handler =<< decode (RiverLibinputDeviceV1AccelProfilesSupport <$> getWord32) body
    21 ->
      handler =<< decode (RiverLibinputDeviceV1AccelProfileDefault <$> getWord32) body
    22 ->
      handler =<< decode (RiverLibinputDeviceV1AccelProfileCurrent <$> getWord32) body
    23 ->
      handler =<< decode (RiverLibinputDeviceV1AccelSpeedDefault <$> getArray) body
    24 ->
      handler =<< decode (RiverLibinputDeviceV1AccelSpeedCurrent <$> getArray) body
    25 ->
      handler =<< decode (RiverLibinputDeviceV1NaturalScrollSupport <$> getInt) body
    26 ->
      handler =<< decode (RiverLibinputDeviceV1NaturalScrollDefault <$> getWord32) body
    27 ->
      handler =<< decode (RiverLibinputDeviceV1NaturalScrollCurrent <$> getWord32) body
    28 ->
      handler =<< decode (RiverLibinputDeviceV1LeftHandedSupport <$> getInt) body
    29 ->
      handler =<< decode (RiverLibinputDeviceV1LeftHandedDefault <$> getWord32) body
    30 ->
      handler =<< decode (RiverLibinputDeviceV1LeftHandedCurrent <$> getWord32) body
    31 ->
      handler =<< decode (RiverLibinputDeviceV1ClickMethodSupport <$> getWord32) body
    32 ->
      handler =<< decode (RiverLibinputDeviceV1ClickMethodDefault <$> getWord32) body
    33 ->
      handler =<< decode (RiverLibinputDeviceV1ClickMethodCurrent <$> getWord32) body
    34 ->
      handler =<< decode (RiverLibinputDeviceV1ClickfingerButtonMapDefault <$> getWord32) body
    35 ->
      handler =<< decode (RiverLibinputDeviceV1ClickfingerButtonMapCurrent <$> getWord32) body
    36 ->
      handler =<< decode (RiverLibinputDeviceV1MiddleEmulationSupport <$> getInt) body
    37 ->
      handler =<< decode (RiverLibinputDeviceV1MiddleEmulationDefault <$> getWord32) body
    38 ->
      handler =<< decode (RiverLibinputDeviceV1MiddleEmulationCurrent <$> getWord32) body
    39 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollMethodSupport <$> getWord32) body
    40 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollMethodDefault <$> getWord32) body
    41 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollMethodCurrent <$> getWord32) body
    42 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollButtonDefault <$> getWord32) body
    43 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollButtonCurrent <$> getWord32) body
    44 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollButtonLockDefault <$> getWord32) body
    45 ->
      handler =<< decode (RiverLibinputDeviceV1ScrollButtonLockCurrent <$> getWord32) body
    46 ->
      handler =<< decode (RiverLibinputDeviceV1DwtSupport <$> getInt) body
    47 ->
      handler =<< decode (RiverLibinputDeviceV1DwtDefault <$> getWord32) body
    48 ->
      handler =<< decode (RiverLibinputDeviceV1DwtCurrent <$> getWord32) body
    49 ->
      handler =<< decode (RiverLibinputDeviceV1DwtpSupport <$> getInt) body
    50 ->
      handler =<< decode (RiverLibinputDeviceV1DwtpDefault <$> getWord32) body
    51 ->
      handler =<< decode (RiverLibinputDeviceV1DwtpCurrent <$> getWord32) body
    52 ->
      handler =<< decode (RiverLibinputDeviceV1RotationSupport <$> getInt) body
    53 ->
      handler =<< decode (RiverLibinputDeviceV1RotationDefault <$> getWord32) body
    54 ->
      handler =<< decode (RiverLibinputDeviceV1RotationCurrent <$> getWord32) body
    55 -> handler RiverLibinputDeviceV1Done
    _ -> handler (RiverLibinputDeviceV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_libinput_accel_config_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLibinputAccelConfigV1Interface :: ByteString
riverLibinputAccelConfigV1Interface = "river_libinput_accel_config_v1"

-- | The highest version these bindings were generated against.
riverLibinputAccelConfigV1Version :: Word32
riverLibinputAccelConfigV1Version = 1

-- | @river_libinput_accel_config_v1.error.invalid_arg@
riverLibinputAccelConfigV1ErrorInvalidArg :: Word32
riverLibinputAccelConfigV1ErrorInvalidArg = 0

-- | @river_libinput_accel_config_v1.accel_type.fallback@
riverLibinputAccelConfigV1AccelTypeFallback :: Word32
riverLibinputAccelConfigV1AccelTypeFallback = 0

-- | @river_libinput_accel_config_v1.accel_type.motion@
riverLibinputAccelConfigV1AccelTypeMotion :: Word32
riverLibinputAccelConfigV1AccelTypeMotion = 1

-- | @river_libinput_accel_config_v1.accel_type.scroll@
riverLibinputAccelConfigV1AccelTypeScroll :: Word32
riverLibinputAccelConfigV1AccelTypeScroll = 2

-- | @river_libinput_accel_config_v1.destroy@
riverLibinputAccelConfigV1Destroy :: Connection -> ObjectId -> IO ()
riverLibinputAccelConfigV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_libinput_accel_config_v1.set_points@
riverLibinputAccelConfigV1SetPoints :: Connection -> ObjectId -> Word32 -> ByteString -> ByteString -> IO ObjectId
riverLibinputAccelConfigV1SetPoints conn self type_ step points =
  requestNew conn self 1 (\result -> argObject result <> argUInt type_ <> argArray step <> argArray points)

-- | Events delivered to a @river_libinput_accel_config_v1@.
data RiverLibinputAccelConfigV1Event
  = RiverLibinputAccelConfigV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_libinput_accel_config_v1@ object.
riverLibinputAccelConfigV1Listen :: Connection -> ObjectId -> (RiverLibinputAccelConfigV1Event -> IO ()) -> IO ()
riverLibinputAccelConfigV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverLibinputAccelConfigV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_libinput_result_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLibinputResultV1Interface :: ByteString
riverLibinputResultV1Interface = "river_libinput_result_v1"

-- | The highest version these bindings were generated against.
riverLibinputResultV1Version :: Word32
riverLibinputResultV1Version = 1

-- | Events delivered to a @river_libinput_result_v1@.
data RiverLibinputResultV1Event
  = RiverLibinputResultV1Success
  | RiverLibinputResultV1Unsupported
  | RiverLibinputResultV1Invalid
  | RiverLibinputResultV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_libinput_result_v1@ object.
riverLibinputResultV1Listen :: Connection -> ObjectId -> (RiverLibinputResultV1Event -> IO ()) -> IO ()
riverLibinputResultV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverLibinputResultV1Success
    1 -> handler RiverLibinputResultV1Unsupported
    2 -> handler RiverLibinputResultV1Invalid
    _ -> handler (RiverLibinputResultV1Unknown opcode body)

