-- | Bindings for @virtual-keyboard-unstable-v1.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.VirtualKeyboard
  (
    ZwpVirtualKeyboardV1Event(..)
  , zwpVirtualKeyboardV1Interface
  , zwpVirtualKeyboardV1Version
  , zwpVirtualKeyboardV1Listen
  , zwpVirtualKeyboardV1Keymap
  , zwpVirtualKeyboardV1Key
  , zwpVirtualKeyboardV1Modifiers
  , zwpVirtualKeyboardV1Destroy
  , zwpVirtualKeyboardV1ErrorNoKeymap
  , ZwpVirtualKeyboardManagerV1Event(..)
  , zwpVirtualKeyboardManagerV1Interface
  , zwpVirtualKeyboardManagerV1Version
  , zwpVirtualKeyboardManagerV1Listen
  , zwpVirtualKeyboardManagerV1CreateVirtualKeyboard
  , zwpVirtualKeyboardManagerV1ErrorUnauthorized
  ) where

import Data.ByteString (ByteString)
import Data.Word (Word16, Word32)
import System.Posix.Types (Fd)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- zwp_virtual_keyboard_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
zwpVirtualKeyboardV1Interface :: ByteString
zwpVirtualKeyboardV1Interface = "zwp_virtual_keyboard_v1"

-- | The highest version these bindings were generated against.
zwpVirtualKeyboardV1Version :: Word32
zwpVirtualKeyboardV1Version = 1

-- | @zwp_virtual_keyboard_v1.error.no_keymap@
zwpVirtualKeyboardV1ErrorNoKeymap :: Word32
zwpVirtualKeyboardV1ErrorNoKeymap = 0

-- | @zwp_virtual_keyboard_v1.keymap@
zwpVirtualKeyboardV1Keymap :: Connection -> ObjectId -> Word32 -> Fd -> Word32 -> IO ()
zwpVirtualKeyboardV1Keymap conn self format fd size =
  requestWithFds conn self 0 (argUInt format <> mempty <> argUInt size) [fd]

-- | @zwp_virtual_keyboard_v1.key@
zwpVirtualKeyboardV1Key :: Connection -> ObjectId -> Word32 -> Word32 -> Word32 -> IO ()
zwpVirtualKeyboardV1Key conn self time key state =
  request conn self 1 (argUInt time <> argUInt key <> argUInt state)

-- | @zwp_virtual_keyboard_v1.modifiers@
zwpVirtualKeyboardV1Modifiers :: Connection -> ObjectId -> Word32 -> Word32 -> Word32 -> Word32 -> IO ()
zwpVirtualKeyboardV1Modifiers conn self modsDepressed modsLatched modsLocked group =
  request conn self 2 (argUInt modsDepressed <> argUInt modsLatched <> argUInt modsLocked <> argUInt group)

-- | @zwp_virtual_keyboard_v1.destroy@
-- Since version 1.
zwpVirtualKeyboardV1Destroy :: Connection -> ObjectId -> IO ()
zwpVirtualKeyboardV1Destroy conn self =
  request conn self 3 (mempty)
    >> freeObject conn self

-- | Events delivered to a @zwp_virtual_keyboard_v1@.
data ZwpVirtualKeyboardV1Event
  = ZwpVirtualKeyboardV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @zwp_virtual_keyboard_v1@ object.
zwpVirtualKeyboardV1Listen :: Connection -> ObjectId -> (ZwpVirtualKeyboardV1Event -> IO ()) -> IO ()
zwpVirtualKeyboardV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (ZwpVirtualKeyboardV1Unknown opcode body)

--------------------------------------------------------------------------------
-- zwp_virtual_keyboard_manager_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
zwpVirtualKeyboardManagerV1Interface :: ByteString
zwpVirtualKeyboardManagerV1Interface = "zwp_virtual_keyboard_manager_v1"

-- | The highest version these bindings were generated against.
zwpVirtualKeyboardManagerV1Version :: Word32
zwpVirtualKeyboardManagerV1Version = 1

-- | @zwp_virtual_keyboard_manager_v1.error.unauthorized@
zwpVirtualKeyboardManagerV1ErrorUnauthorized :: Word32
zwpVirtualKeyboardManagerV1ErrorUnauthorized = 0

-- | @zwp_virtual_keyboard_manager_v1.create_virtual_keyboard@
zwpVirtualKeyboardManagerV1CreateVirtualKeyboard :: Connection -> ObjectId -> ObjectId -> IO ObjectId
zwpVirtualKeyboardManagerV1CreateVirtualKeyboard conn self seat =
  do
    id_ <- newObject conn
    request conn self 0 (argObject seat <> argObject id_)
    pure id_

-- | Events delivered to a @zwp_virtual_keyboard_manager_v1@.
data ZwpVirtualKeyboardManagerV1Event
  = ZwpVirtualKeyboardManagerV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @zwp_virtual_keyboard_manager_v1@ object.
zwpVirtualKeyboardManagerV1Listen :: Connection -> ObjectId -> (ZwpVirtualKeyboardManagerV1Event -> IO ()) -> IO ()
zwpVirtualKeyboardManagerV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (ZwpVirtualKeyboardManagerV1Unknown opcode body)

