-- | Bindings for @river-xkb-config-v1.xml@.
--
-- Generated by @util/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.XkbConfig
  (
    RiverXkbConfigV1Event(..)
  , riverXkbConfigV1Interface
  , riverXkbConfigV1Version
  , riverXkbConfigV1Listen
  , riverXkbConfigV1Stop
  , riverXkbConfigV1Destroy
  , riverXkbConfigV1CreateKeymap
  , riverXkbConfigV1ErrorInvalidDestroy
  , riverXkbConfigV1ErrorInvalidFormat
  , riverXkbConfigV1KeymapFormatTextV1
  , riverXkbConfigV1KeymapFormatTextV2
  , RiverXkbKeymapV1Event(..)
  , riverXkbKeymapV1Interface
  , riverXkbKeymapV1Version
  , riverXkbKeymapV1Listen
  , riverXkbKeymapV1Destroy
  , RiverXkbKeyboardV1Event(..)
  , riverXkbKeyboardV1Interface
  , riverXkbKeyboardV1Version
  , riverXkbKeyboardV1Listen
  , riverXkbKeyboardV1Destroy
  , riverXkbKeyboardV1SetKeymap
  , riverXkbKeyboardV1SetLayoutByIndex
  , riverXkbKeyboardV1SetLayoutByName
  , riverXkbKeyboardV1CapslockEnable
  , riverXkbKeyboardV1CapslockDisable
  , riverXkbKeyboardV1NumlockEnable
  , riverXkbKeyboardV1NumlockDisable
  , riverXkbKeyboardV1ScrolllockEnable
  , riverXkbKeyboardV1ScrolllockDisable
  , riverXkbKeyboardV1ErrorInvalidKeymap
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)
import System.Posix.Types (Fd)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_xkb_config_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbConfigV1Interface :: ByteString
riverXkbConfigV1Interface = "river_xkb_config_v1"

-- | The highest version these bindings were generated against.
riverXkbConfigV1Version :: Word32
riverXkbConfigV1Version = 3

-- | @river_xkb_config_v1.error.invalid_destroy@
riverXkbConfigV1ErrorInvalidDestroy :: Word32
riverXkbConfigV1ErrorInvalidDestroy = 0

-- | @river_xkb_config_v1.error.invalid_format@
riverXkbConfigV1ErrorInvalidFormat :: Word32
riverXkbConfigV1ErrorInvalidFormat = 1

-- | @river_xkb_config_v1.keymap_format.text_v1@
riverXkbConfigV1KeymapFormatTextV1 :: Word32
riverXkbConfigV1KeymapFormatTextV1 = 1

-- | @river_xkb_config_v1.keymap_format.text_v2@
riverXkbConfigV1KeymapFormatTextV2 :: Word32
riverXkbConfigV1KeymapFormatTextV2 = 2

-- | @river_xkb_config_v1.stop@
riverXkbConfigV1Stop :: Connection -> ObjectId -> IO ()
riverXkbConfigV1Stop conn self =
  request conn self 0 (mempty)

-- | @river_xkb_config_v1.destroy@
riverXkbConfigV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbConfigV1Destroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | @river_xkb_config_v1.create_keymap@
riverXkbConfigV1CreateKeymap :: Connection -> ObjectId -> Fd -> Word32 -> IO ObjectId
riverXkbConfigV1CreateKeymap conn self fd format =
  requestNewWithFds conn self 2 (\id_ -> argObject id_ <> mempty <> argUInt format) [fd]

-- | Events delivered to a @river_xkb_config_v1@.
data RiverXkbConfigV1Event
  = RiverXkbConfigV1Finished
  | RiverXkbConfigV1XkbKeyboard !ObjectId
  | RiverXkbConfigV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_config_v1@ object.
riverXkbConfigV1Listen :: Connection -> ObjectId -> (RiverXkbConfigV1Event -> IO ()) -> IO ()
riverXkbConfigV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverXkbConfigV1Finished
    1 ->
      handler =<< decode (RiverXkbConfigV1XkbKeyboard <$> getObject) body
    _ -> handler (RiverXkbConfigV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_xkb_keymap_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbKeymapV1Interface :: ByteString
riverXkbKeymapV1Interface = "river_xkb_keymap_v1"

-- | The highest version these bindings were generated against.
riverXkbKeymapV1Version :: Word32
riverXkbKeymapV1Version = 3

-- | @river_xkb_keymap_v1.destroy@
riverXkbKeymapV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbKeymapV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | Events delivered to a @river_xkb_keymap_v1@.
data RiverXkbKeymapV1Event
  = RiverXkbKeymapV1Success
  | RiverXkbKeymapV1Failure !ByteString
  | RiverXkbKeymapV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_keymap_v1@ object.
riverXkbKeymapV1Listen :: Connection -> ObjectId -> (RiverXkbKeymapV1Event -> IO ()) -> IO ()
riverXkbKeymapV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverXkbKeymapV1Success
    1 ->
      handler =<< decode (RiverXkbKeymapV1Failure <$> getString) body
    _ -> handler (RiverXkbKeymapV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_xkb_keyboard_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbKeyboardV1Interface :: ByteString
riverXkbKeyboardV1Interface = "river_xkb_keyboard_v1"

-- | The highest version these bindings were generated against.
riverXkbKeyboardV1Version :: Word32
riverXkbKeyboardV1Version = 3

-- | @river_xkb_keyboard_v1.error.invalid_keymap@
riverXkbKeyboardV1ErrorInvalidKeymap :: Word32
riverXkbKeyboardV1ErrorInvalidKeymap = 0

-- | @river_xkb_keyboard_v1.destroy@
riverXkbKeyboardV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_xkb_keyboard_v1.set_keymap@
riverXkbKeyboardV1SetKeymap :: Connection -> ObjectId -> ObjectId -> IO ()
riverXkbKeyboardV1SetKeymap conn self keymap =
  request conn self 1 (argObject keymap)

-- | @river_xkb_keyboard_v1.set_layout_by_index@
riverXkbKeyboardV1SetLayoutByIndex :: Connection -> ObjectId -> Int32 -> IO ()
riverXkbKeyboardV1SetLayoutByIndex conn self index =
  request conn self 2 (argInt index)

-- | @river_xkb_keyboard_v1.set_layout_by_name@
riverXkbKeyboardV1SetLayoutByName :: Connection -> ObjectId -> ByteString -> IO ()
riverXkbKeyboardV1SetLayoutByName conn self name =
  request conn self 3 (argString (Just name))

-- | @river_xkb_keyboard_v1.capslock_enable@
riverXkbKeyboardV1CapslockEnable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1CapslockEnable conn self =
  request conn self 4 (mempty)

-- | @river_xkb_keyboard_v1.capslock_disable@
riverXkbKeyboardV1CapslockDisable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1CapslockDisable conn self =
  request conn self 5 (mempty)

-- | @river_xkb_keyboard_v1.numlock_enable@
riverXkbKeyboardV1NumlockEnable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1NumlockEnable conn self =
  request conn self 6 (mempty)

-- | @river_xkb_keyboard_v1.numlock_disable@
riverXkbKeyboardV1NumlockDisable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1NumlockDisable conn self =
  request conn self 7 (mempty)

-- | @river_xkb_keyboard_v1.scrolllock_enable@
-- Since version 3.
riverXkbKeyboardV1ScrolllockEnable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1ScrolllockEnable conn self =
  request conn self 8 (mempty)

-- | @river_xkb_keyboard_v1.scrolllock_disable@
-- Since version 3.
riverXkbKeyboardV1ScrolllockDisable :: Connection -> ObjectId -> IO ()
riverXkbKeyboardV1ScrolllockDisable conn self =
  request conn self 9 (mempty)

-- | Events delivered to a @river_xkb_keyboard_v1@.
data RiverXkbKeyboardV1Event
  = RiverXkbKeyboardV1Removed
  | RiverXkbKeyboardV1InputDevice !ObjectId
  | RiverXkbKeyboardV1Layout !Word32 !(Maybe ByteString)
  | RiverXkbKeyboardV1CapslockEnabled
  | RiverXkbKeyboardV1CapslockDisabled
  | RiverXkbKeyboardV1NumlockEnabled
  | RiverXkbKeyboardV1NumlockDisabled
  | RiverXkbKeyboardV1Done
  | RiverXkbKeyboardV1ScrolllockEnabled
  | RiverXkbKeyboardV1ScrolllockDisabled
  | RiverXkbKeyboardV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_keyboard_v1@ object.
riverXkbKeyboardV1Listen :: Connection -> ObjectId -> (RiverXkbKeyboardV1Event -> IO ()) -> IO ()
riverXkbKeyboardV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverXkbKeyboardV1Removed
    1 ->
      handler =<< decode (RiverXkbKeyboardV1InputDevice <$> getObject) body
    2 ->
      handler =<< decode (RiverXkbKeyboardV1Layout <$> getWord32 <*> getStringMaybe) body
    3 -> handler RiverXkbKeyboardV1CapslockEnabled
    4 -> handler RiverXkbKeyboardV1CapslockDisabled
    5 -> handler RiverXkbKeyboardV1NumlockEnabled
    6 -> handler RiverXkbKeyboardV1NumlockDisabled
    7 -> handler RiverXkbKeyboardV1Done
    8 -> handler RiverXkbKeyboardV1ScrolllockEnabled
    9 -> handler RiverXkbKeyboardV1ScrolllockDisabled
    _ -> handler (RiverXkbKeyboardV1Unknown opcode body)

