#!/usr/bin/env bash
#
# Regenerate src-river/XMonad/River/Keysym.hs from the X11 package's own values.
#
# Usage: codegen/gen-keysyms.sh
#
# Only needed when the set of keysyms changes, which in practice means bumping
# the X11 dependency.  The output is checked in.
#
# The values are read out of a real X11 build rather than transcribed, and that
# is the whole point: xkbcommon reuses X11's keysym numbering wholesale, so the
# numbers have to be *right*, and inventing 347 of them from memory is how you
# ship a config where one key silently stops working.  Reading them from the
# package that already has them makes the correspondence true by construction.
#
# The name list comes from upstream xmonad's recorded API, so a keysym upstream
# re-exports but this script missed would show up as a golden diff rather than
# as a key that mysteriously does nothing.

set -euo pipefail

cd "$(dirname "$0")/.."

out=src-river/XMonad/River/Keysym.hs
golden=tests/api/upstream/xmonad-reexports.golden

[ -f "$golden" ] || { echo "gen-keysyms: need $golden; record it with\n  tests/api/dump-api.sh tests/api/upstream ../xmonad" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

grep -E '^XMonad \| xK_' "$golden" | cut -d'|' -f2 | tr -d ' ' | sort -u > "$tmp/names"

{
    echo 'module Main (main) where'
    echo 'import Graphics.X11'
    echo 'main :: IO ()'
    echo 'main = do'
    sed 's/.*/  putStrLn ("&" ++ " " ++ show (toInteger &))/' "$tmp/names"
} > "$tmp/probe.hs"

stack exec --package X11 -- ghc -v0 -ignore-dot-ghci -o "$tmp/probe" "$tmp/probe.hs"
"$tmp/probe" > "$tmp/values"

python3 - "$tmp/values" "$out" <<'PY'
import sys
vals = [l.split() for l in open(sys.argv[1])]
names = [n for n, _ in vals]

header = '''-- | Keysyms, with X11's values.
--
-- GENERATED by codegen/gen-keysyms.sh -- do not edit.
--
-- Not a compatibility shim.  xkbcommon reuses X11's keysym numbering
-- wholesale, and @river_xkb_bindings_v1.get_xkb_binding@ takes an xkbcommon
-- keysym directly, so @xK_Return@ is 0xff0d on both sides and a key
-- description means the same thing without translation.  That is one of the
-- two coincidences this port rests on; the other is that
-- @river_seat_v1.modifiers@ reuses X11's modifier mask values.
--
-- The values are read out of the X11 package rather than transcribed, because
-- inventing this many constants by hand is how you ship a config where one key
-- silently stops working.
module XMonad.River.Keysym (
  noSymbol, stringToKeysym, keysymToString,
%%NAMES%%
  ) where

import Data.Char (chr, ord)
import qualified Data.Map.Strict as M

import XMonad.River.Keysym.Table (keysymTable, reverseKeysymTable)
import XMonad.River.Types (KeySym)

-- | The keysym meaning "no key".  Zero, as XKB_KEY_NoSymbol is.
noSymbol :: KeySym
noSymbol = 0

-- | Parse a key name in X11\'s spelling, as "XMonad.Util.EZConfig" key
-- descriptions use.
--
-- Printable Latin-1 maps to its own code point, which is how X11 -- and
-- therefore xkbcommon -- numbers that range; everything else comes from the
-- table below.  Returns \'noSymbol\' for an unknown name, matching X11.
stringToKeysym :: String -> KeySym
stringToKeysym name = case M.lookup name keysymTable of
  Just ks -> ks
  Nothing -> case name of
    [c] | ord c >= 0x20 && ord c <= 0xff -> fromIntegral (ord c)
    _ -> noSymbol

-- | Inverse of \'stringToKeysym\'.
keysymToString :: KeySym -> String
keysymToString ks = case M.lookup ks reverseKeysymTable of
  Just name -> name
  Nothing
    | ks >= 0x20 && ks <= 0xff -> [chr (fromIntegral ks)]
    | otherwise -> "0x" ++ showHex ks
  where
    showHex 0 = "0"
    showHex n = go n ""
      where
        go 0 acc = acc
        go m acc = go (m `div` 16) (digit (m `mod` 16) : acc)
        digit d | d < 10 = chr (ord '0' + fromIntegral d)
                | otherwise = chr (ord 'a' + fromIntegral d - 10)

'''

names_block = []
for i in range(0, len(names), 6):
    names_block.append("  " + ", ".join(names[i:i + 6]) + ("," if i + 6 < len(names) else ""))
header = header.replace("%%NAMES%%", "\n".join(names_block))

lines = [header]
# Continuation lines of a type signature must be indented, or they start a new
# declaration.
for i in range(0, len(names), 8):
    chunk = ", ".join(names[i:i + 8])
    prefix = "" if i == 0 else "  "
    suffix = " :: KeySym" if i + 8 >= len(names) else ","
    lines.append(prefix + chunk + suffix)
lines.append("")
lines += [f"{n} = {v}" for n, v in vals]

open(sys.argv[2], "w").write("\n".join(lines) + "\n")

tbl = ['''-- | Keysym name lookup tables.
--
-- GENERATED by codegen/gen-keysyms.sh -- do not edit.
--
-- Separate from "XMonad.River.Keysym" so that "XMonad.Core" can re-export the
-- keysyms -- which exist on both backends -- without also exporting these,
-- which do not.  Anything river-specific is reachable only through
-- "XMonad.River".
module XMonad.River.Keysym.Table (keysymTable, reverseKeysymTable) where

import qualified Data.Map.Strict as M

import XMonad.River.Types (KeySym)

-- | Every keysym, keyed by the name X11 gives it.
keysymTable :: M.Map String KeySym
keysymTable = M.fromList''']
for i, (n, v) in enumerate(vals):
    tbl.append(("  [ " if i == 0 else "  , ") + f'("{n[3:]}", {v})')
tbl.append("  ]")
tbl.append("")
tbl.append("-- | The inverse of 'keysymTable'.")
tbl.append("reverseKeysymTable :: M.Map KeySym String")
tbl.append("reverseKeysymTable = M.fromList [ (v, k) | (k, v) <- M.toList keysymTable ]")
import os
open(os.path.join(os.path.dirname(sys.argv[2]), "Keysym", "Table.hs"), "w").write("\n".join(tbl) + "\n")
print(f"gen-keysyms: wrote {len(vals)} keysyms to {sys.argv[2]} and its Table")
PY
